/**
 * Equipment Library for Arianrhod 2E
 * Contains all standard equipment from the rulebook.
 */

const weapons = [
  // ===== Unarmed (格闘/격투) =====
  {
    id: "w_bare_fist",
    name: "素手",
    nameKo: "맨손",
    nameEn: "Bare Fist",
    category: "unarmed",
    cl: 1,
    weight: 0,
    accuracy: 0,
    attack: 0,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 0,
    note: ""
  },
  {
    id: "w_iron_knuckle",
    name: "アイアンナックル",
    nameKo: "아이언너클",
    nameEn: "Iron Knuckle",
    category: "unarmed",
    cl: 1,
    weight: 5,
    accuracy: 1,
    attack: 4,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 10,
    note: ""
  },
  {
    id: "w_bagh_nakh",
    name: "バグナウ",
    nameKo: "바그나우",
    nameEn: "Bagh Nakh",
    category: "unarmed",
    cl: 1,
    weight: 5,
    accuracy: 0,
    attack: 6,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 50,
    note: ""
  },
  {
    id: "w_katar",
    name: "カタール",
    nameKo: "카타르",
    nameEn: "Katar",
    category: "unarmed",
    cl: 2,
    weight: 5,
    accuracy: 1,
    attack: 7,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 100,
    note: ""
  },
  {
    id: "w_cestus",
    name: "セスタス",
    nameKo: "세스터스",
    nameEn: "Cestus",
    category: "unarmed",
    cl: 3,
    weight: 5,
    accuracy: 1,
    attack: 8,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 300,
    note: ""
  },
  {
    id: "w_jamadhar",
    name: "ジャマダハル",
    nameKo: "자마다할",
    nameEn: "Jamadhar",
    category: "unarmed",
    cl: 5,
    weight: 5,
    accuracy: 1,
    attack: 10,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 700,
    note: ""
  },
  {
    id: "w_mithril_knuckle",
    name: "ミスリルナックル",
    nameKo: "미스릴너클",
    nameEn: "Mithril Knuckle",
    category: "unarmed",
    cl: 7,
    weight: 5,
    accuracy: 2,
    attack: 12,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 1800,
    note: ""
  },
  {
    id: "w_diamond_knuckle",
    name: "ダイヤナックル",
    nameKo: "다이아너클",
    nameEn: "Diamond Knuckle",
    category: "unarmed",
    cl: 10,
    weight: 5,
    accuracy: 2,
    attack: 15,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 5000,
    note: ""
  },

  // ===== Dagger (短剣/단검) =====
  {
    id: "w_knife",
    name: "ナイフ",
    nameKo: "나이프",
    nameEn: "Knife",
    category: "dagger",
    cl: 1,
    weight: 1,
    accuracy: 0,
    attack: 3,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 10,
    note: ""
  },
  {
    id: "w_dagger",
    name: "ダガー",
    nameKo: "대거",
    nameEn: "Dagger",
    category: "dagger",
    cl: 1,
    weight: 1,
    accuracy: 0,
    attack: 4,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 20,
    note: ""
  },
  {
    id: "w_stiletto",
    name: "スティレット",
    nameKo: "스틸레토",
    nameEn: "Stiletto",
    category: "dagger",
    cl: 2,
    weight: 2,
    accuracy: 0,
    attack: 5,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 120,
    note: ""
  },
  {
    id: "w_swordbreaker",
    name: "ソードブレイカー",
    nameKo: "소드브레이커",
    nameEn: "Swordbreaker",
    category: "dagger",
    cl: 3,
    weight: 2,
    accuracy: 0,
    attack: 4,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 300,
    note: "+1 physDef"
  },
  {
    id: "w_kunai",
    name: "クナイ",
    nameKo: "쿠나이",
    nameEn: "Kunai",
    category: "dagger",
    cl: 3,
    weight: 1,
    accuracy: 0,
    attack: 6,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 350,
    note: ""
  },
  {
    id: "w_main_gauche",
    name: "マインゴーシュ",
    nameKo: "마인고슈",
    nameEn: "Main Gauche",
    category: "dagger",
    cl: 5,
    weight: 2,
    accuracy: 1,
    attack: 6,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 700,
    note: ""
  },
  {
    id: "w_mithril_dagger",
    name: "ミスリルダガー",
    nameKo: "미스릴대거",
    nameEn: "Mithril Dagger",
    category: "dagger",
    cl: 7,
    weight: 2,
    accuracy: 1,
    attack: 8,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 1800,
    note: ""
  },
  {
    id: "w_diamond_dagger",
    name: "ダイヤダガー",
    nameKo: "다이아대거",
    nameEn: "Diamond Dagger",
    category: "dagger",
    cl: 10,
    weight: 2,
    accuracy: 2,
    attack: 10,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 5000,
    note: ""
  },

  // ===== Longsword (長剣/장검) =====
  {
    id: "w_short_sword",
    name: "ショートソード",
    nameKo: "숏소드",
    nameEn: "Short Sword",
    category: "longsword",
    cl: 1,
    weight: 2,
    accuracy: 0,
    attack: 5,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 80,
    note: ""
  },
  {
    id: "w_long_sword",
    name: "ロングソード",
    nameKo: "롱소드",
    nameEn: "Long Sword",
    category: "longsword",
    cl: 1,
    weight: 4,
    accuracy: 0,
    attack: 7,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 200,
    note: ""
  },
  {
    id: "w_bastard_sword",
    name: "バスタードソード",
    nameKo: "바스타드소드",
    nameEn: "Bastard Sword",
    category: "longsword",
    cl: 2,
    weight: 8,
    accuracy: -2,
    attack: 8,
    initiativeMod: -1,
    range: 0,
    slot: "versatile",
    price: 260,
    note: ""
  },
  {
    id: "w_shamshir",
    name: "シャムシール",
    nameKo: "샴시르",
    nameEn: "Shamshir",
    category: "longsword",
    cl: 3,
    weight: 5,
    accuracy: 0,
    attack: 8,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 500,
    note: ""
  },
  {
    id: "w_falchion",
    name: "ファルシオン",
    nameKo: "팔시온",
    nameEn: "Falchion",
    category: "longsword",
    cl: 5,
    weight: 6,
    accuracy: 0,
    attack: 10,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 1200,
    note: ""
  },
  {
    id: "w_mithril_sword",
    name: "ミスリルソード",
    nameKo: "미스릴소드",
    nameEn: "Mithril Sword",
    category: "longsword",
    cl: 7,
    weight: 7,
    accuracy: 0,
    attack: 12,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 2500,
    note: ""
  },
  {
    id: "w_diamond_sword",
    name: "ダイヤソード",
    nameKo: "다이아소드",
    nameEn: "Diamond Sword",
    category: "longsword",
    cl: 10,
    weight: 8,
    accuracy: 1,
    attack: 14,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 6000,
    note: ""
  },

  // ===== Greatsword (両手剣/양손검) =====
  {
    id: "w_zweihander",
    name: "ツヴァイヘンダー",
    nameKo: "츠바이헨더",
    nameEn: "Zweihander",
    category: "greatsword",
    cl: 1,
    weight: 10,
    accuracy: -1,
    attack: 10,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 250,
    note: ""
  },
  {
    id: "w_greatsword",
    name: "グレートソード",
    nameKo: "그레이트소드",
    nameEn: "Greatsword",
    category: "greatsword",
    cl: 1,
    weight: 10,
    accuracy: -1,
    attack: 11,
    initiativeMod: -3,
    range: 0,
    slot: "twoHand",
    price: 300,
    note: ""
  },
  {
    id: "w_flamberge",
    name: "フランベルジュ",
    nameKo: "플랑베르주",
    nameEn: "Flamberge",
    category: "greatsword",
    cl: 3,
    weight: 10,
    accuracy: -1,
    attack: 13,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 800,
    note: ""
  },
  {
    id: "w_claymore",
    name: "クレイモア",
    nameKo: "클레이모어",
    nameEn: "Claymore",
    category: "greatsword",
    cl: 5,
    weight: 12,
    accuracy: -1,
    attack: 15,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 1500,
    note: ""
  },
  {
    id: "w_mithril_claymore",
    name: "ミスリルクレイモア",
    nameKo: "미스릴 클레이모어",
    nameEn: "Mithril Claymore",
    category: "greatsword",
    cl: 7,
    weight: 13,
    accuracy: -1,
    attack: 17,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 3000,
    note: ""
  },
  {
    id: "w_diamond_claymore",
    name: "ダイヤクレイモア",
    nameKo: "다이아 클레이모어",
    nameEn: "Diamond Claymore",
    category: "greatsword",
    cl: 10,
    weight: 14,
    accuracy: 0,
    attack: 20,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 7500,
    note: ""
  },

  // ===== Axe (斧/도끼) =====
  {
    id: "w_hand_axe",
    name: "ハンドアクス",
    nameKo: "핸드액스",
    nameEn: "Hand Axe",
    category: "axe",
    cl: 1,
    weight: 8,
    accuracy: -2,
    attack: 8,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 100,
    note: ""
  },
  {
    id: "w_great_axe",
    name: "グレートアクス",
    nameKo: "그레이트액스",
    nameEn: "Great Axe",
    category: "axe",
    cl: 1,
    weight: 10,
    accuracy: -2,
    attack: 11,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 160,
    note: ""
  },
  {
    id: "w_battle_axe",
    name: "バトルアクス",
    nameKo: "배틀액스",
    nameEn: "Battle Axe",
    category: "axe",
    cl: 3,
    weight: 10,
    accuracy: -1,
    attack: 13,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 500,
    note: ""
  },
  {
    id: "w_halberd",
    name: "ハルバード",
    nameKo: "할버드",
    nameEn: "Halberd",
    category: "axe",
    cl: 5,
    weight: 12,
    accuracy: -1,
    attack: 15,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 1200,
    note: ""
  },
  {
    id: "w_mithril_axe",
    name: "ミスリルアクス",
    nameKo: "미스릴액스",
    nameEn: "Mithril Axe",
    category: "axe",
    cl: 7,
    weight: 13,
    accuracy: -1,
    attack: 17,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 2800,
    note: ""
  },
  {
    id: "w_diamond_axe",
    name: "ダイヤアクス",
    nameKo: "다이아액스",
    nameEn: "Diamond Axe",
    category: "axe",
    cl: 10,
    weight: 14,
    accuracy: 0,
    attack: 20,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 6500,
    note: ""
  },

  // ===== Spear (槍/창) =====
  {
    id: "w_javelin",
    name: "ジャベリン",
    nameKo: "자벨린",
    nameEn: "Javelin",
    category: "spear",
    cl: 1,
    weight: 3,
    accuracy: -1,
    attack: 5,
    initiativeMod: 0,
    range: 10,
    slot: "oneHand",
    price: 30,
    note: ""
  },
  {
    id: "w_spear",
    name: "スピア",
    nameKo: "스피어",
    nameEn: "Spear",
    category: "spear",
    cl: 1,
    weight: 8,
    accuracy: -1,
    attack: 8,
    initiativeMod: -1,
    range: 0,
    slot: "twoHand",
    price: 60,
    note: ""
  },
  {
    id: "w_trident",
    name: "トライデント",
    nameKo: "트라이덴트",
    nameEn: "Trident",
    category: "spear",
    cl: 2,
    weight: 8,
    accuracy: -1,
    attack: 9,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 180,
    note: ""
  },
  {
    id: "w_lance",
    name: "ランス",
    nameKo: "랜스",
    nameEn: "Lance",
    category: "spear",
    cl: 1,
    weight: 8,
    accuracy: -1,
    attack: 8,
    initiativeMod: -2,
    range: 0,
    slot: "oneHand",
    price: 100,
    note: "Mounted only"
  },
  {
    id: "w_pike",
    name: "パイク",
    nameKo: "파이크",
    nameEn: "Pike",
    category: "spear",
    cl: 5,
    weight: 13,
    accuracy: 0,
    attack: 13,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 900,
    note: ""
  },
  {
    id: "w_mithril_spear",
    name: "ミスリルスピア",
    nameKo: "미스릴 스피어",
    nameEn: "Mithril Spear",
    category: "spear",
    cl: 7,
    weight: 10,
    accuracy: 0,
    attack: 15,
    initiativeMod: -1,
    range: 0,
    slot: "twoHand",
    price: 2500,
    note: ""
  },

  // ===== Whip (鞭/채찍) =====
  {
    id: "w_whip",
    name: "ウィップ",
    nameKo: "윕",
    nameEn: "Whip",
    category: "whip",
    cl: 1,
    weight: 3,
    accuracy: -2,
    attack: 5,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 30,
    note: ""
  },
  {
    id: "w_chain_whip",
    name: "チェインウィップ",
    nameKo: "체인윕",
    nameEn: "Chain Whip",
    category: "whip",
    cl: 3,
    weight: 4,
    accuracy: -2,
    attack: 7,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 400,
    note: ""
  },
  {
    id: "w_mithril_whip",
    name: "ミスリルウィップ",
    nameKo: "미스릴윕",
    nameEn: "Mithril Whip",
    category: "whip",
    cl: 7,
    weight: 5,
    accuracy: -1,
    attack: 9,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 1500,
    note: ""
  },

  // ===== Blunt (打撃/타격) =====
  {
    id: "w_club",
    name: "クラブ",
    nameKo: "클럽",
    nameEn: "Club",
    category: "blunt",
    cl: 1,
    weight: 1,
    accuracy: -1,
    attack: 2,
    initiativeMod: 0,
    range: 0,
    slot: "oneHand",
    price: 20,
    note: ""
  },
  {
    id: "w_staff",
    name: "スタッフ",
    nameKo: "스태프",
    nameEn: "Staff",
    category: "blunt",
    cl: 1,
    weight: 5,
    accuracy: -1,
    attack: 2,
    initiativeMod: 0,
    range: 0,
    slot: "twoHand",
    price: 40,
    note: "+1 physDef"
  },
  {
    id: "w_mace",
    name: "メイス",
    nameKo: "메이스",
    nameEn: "Mace",
    category: "blunt",
    cl: 1,
    weight: 5,
    accuracy: 0,
    attack: 7,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 100,
    note: ""
  },
  {
    id: "w_war_hammer",
    name: "ウォーハンマー",
    nameKo: "워해머",
    nameEn: "War Hammer",
    category: "blunt",
    cl: 3,
    weight: 8,
    accuracy: -1,
    attack: 11,
    initiativeMod: -2,
    range: 0,
    slot: "twoHand",
    price: 400,
    note: ""
  },
  {
    id: "w_mithril_mace",
    name: "ミスリルメイス",
    nameKo: "미스릴메이스",
    nameEn: "Mithril Mace",
    category: "blunt",
    cl: 7,
    weight: 6,
    accuracy: 0,
    attack: 12,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 2500,
    note: ""
  },
  {
    id: "w_diamond_mace",
    name: "ダイヤメイス",
    nameKo: "다이아메이스",
    nameEn: "Diamond Mace",
    category: "blunt",
    cl: 10,
    weight: 7,
    accuracy: 1,
    attack: 14,
    initiativeMod: -1,
    range: 0,
    slot: "oneHand",
    price: 6000,
    note: ""
  },

  // ===== Bow (弓/활) =====
  {
    id: "w_short_bow",
    name: "ショートボウ",
    nameKo: "숏보우",
    nameEn: "Short Bow",
    category: "bow",
    cl: 1,
    weight: 4,
    accuracy: -2,
    attack: 5,
    initiativeMod: -2,
    range: 20,
    slot: "twoHand",
    price: 120,
    note: ""
  },
  {
    id: "w_long_bow",
    name: "ロングボウ",
    nameKo: "롱보우",
    nameEn: "Long Bow",
    category: "bow",
    cl: 2,
    weight: 6,
    accuracy: -2,
    attack: 7,
    initiativeMod: -3,
    range: 30,
    slot: "twoHand",
    price: 300,
    note: ""
  },
  {
    id: "w_composite_bow",
    name: "コンポジットボウ",
    nameKo: "컴포지트보우",
    nameEn: "Composite Bow",
    category: "bow",
    cl: 5,
    weight: 8,
    accuracy: -1,
    attack: 10,
    initiativeMod: -3,
    range: 30,
    slot: "twoHand",
    price: 1000,
    note: ""
  },
  {
    id: "w_crossbow",
    name: "クロスボウ",
    nameKo: "크로스보우",
    nameEn: "Crossbow",
    category: "bow",
    cl: 3,
    weight: 8,
    accuracy: -1,
    attack: 8,
    initiativeMod: -4,
    range: 30,
    slot: "twoHand",
    price: 500,
    note: ""
  },
  {
    id: "w_mithril_bow",
    name: "ミスリルボウ",
    nameKo: "미스릴보우",
    nameEn: "Mithril Bow",
    category: "bow",
    cl: 7,
    weight: 7,
    accuracy: -1,
    attack: 12,
    initiativeMod: -3,
    range: 30,
    slot: "twoHand",
    price: 2800,
    note: ""
  },
  {
    id: "w_ballista",
    name: "バリスタ",
    nameKo: "발리스타",
    nameEn: "Ballista",
    category: "bow",
    cl: 10,
    weight: 16,
    accuracy: -1,
    attack: 16,
    initiativeMod: -5,
    range: 50,
    slot: "twoHand",
    price: 6000,
    note: ""
  }
];

const armor = [
  // ===== Head (頭/머리) =====
  {
    id: "a_hat",
    name: "帽子",
    nameKo: "모자",
    nameEn: "Hat",
    category: "head",
    cl: 1,
    weight: 1,
    physDef: 1,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 50,
    restriction: "",
    note: ""
  },
  {
    id: "a_helm",
    name: "ヘルム",
    nameKo: "헬름",
    nameEn: "Helm",
    category: "head",
    cl: 1,
    weight: 3,
    physDef: 2,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: 0,
    price: 100,
    restriction: "W",
    note: ""
  },
  {
    id: "a_circlet",
    name: "サークレット",
    nameKo: "서클릿",
    nameEn: "Circlet",
    category: "head",
    cl: 2,
    weight: 1,
    physDef: 1,
    magDef: 1,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 200,
    restriction: "",
    note: ""
  },
  {
    id: "a_hachigane",
    name: "鉢金",
    nameKo: "하치가네",
    nameEn: "Hachigane",
    category: "head",
    cl: 2,
    weight: 2,
    physDef: 3,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: -1,
    price: 250,
    restriction: "",
    note: ""
  },
  {
    id: "a_great_helm",
    name: "グレートヘルム",
    nameKo: "그레이트헬름",
    nameEn: "Great Helm",
    category: "head",
    cl: 3,
    weight: 5,
    physDef: 4,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: 0,
    price: 500,
    restriction: "W",
    note: ""
  },
  {
    id: "a_mithril_helm",
    name: "ミスリルヘルム",
    nameKo: "미스릴헬름",
    nameEn: "Mithril Helm",
    category: "head",
    cl: 7,
    weight: 5,
    physDef: 6,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: 0,
    price: 2500,
    restriction: "W",
    note: ""
  },
  {
    id: "a_diamond_helm",
    name: "ダイヤヘルム",
    nameKo: "다이아헬름",
    nameEn: "Diamond Helm",
    category: "head",
    cl: 10,
    weight: 7,
    physDef: 8,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: 0,
    price: 5800,
    restriction: "W",
    note: ""
  },

  // ===== Body (胴/몸통) =====
  {
    id: "a_robe",
    name: "ローブ",
    nameKo: "로브",
    nameEn: "Robe",
    category: "body",
    cl: 1,
    weight: 2,
    physDef: 2,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 30,
    restriction: "",
    note: ""
  },
  {
    id: "a_leather_armor",
    name: "レザーアーマー",
    nameKo: "레더아머",
    nameEn: "Leather Armor",
    category: "body",
    cl: 1,
    weight: 4,
    physDef: 4,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 150,
    restriction: "",
    note: ""
  },
  {
    id: "a_chainmail",
    name: "チェインメイル",
    nameKo: "체인메일",
    nameEn: "Chainmail",
    category: "body",
    cl: 1,
    weight: 8,
    physDef: 6,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: -1,
    price: 450,
    restriction: "W",
    note: ""
  },
  {
    id: "a_breastplate",
    name: "ブレストプレート",
    nameKo: "브레스트플레이트",
    nameEn: "Breastplate",
    category: "body",
    cl: 3,
    weight: 10,
    physDef: 8,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: -1,
    price: 800,
    restriction: "W",
    note: ""
  },
  {
    id: "a_black_robe",
    name: "黒ローブ",
    nameKo: "검은로브",
    nameEn: "Black Robe",
    category: "body",
    cl: 5,
    weight: 3,
    physDef: 4,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 9800,
    restriction: "A,M",
    note: "INT+1"
  },
  {
    id: "a_plate_mail",
    name: "プレートメイル",
    nameKo: "플레이트메일",
    nameEn: "Plate Mail",
    category: "body",
    cl: 6,
    weight: 12,
    physDef: 12,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: -2,
    price: 3200,
    restriction: "W",
    note: ""
  },
  {
    id: "a_mithril_armor",
    name: "ミスリルアーマー",
    nameKo: "미스릴아머",
    nameEn: "Mithril Armor",
    category: "body",
    cl: 8,
    weight: 13,
    physDef: 13,
    magDef: 0,
    evasion: -1,
    initiativeMod: 0,
    movementMod: -2,
    price: 5800,
    restriction: "W",
    note: ""
  },
  {
    id: "a_diamond_armor",
    name: "ダイヤアーマー",
    nameKo: "다이아아머",
    nameEn: "Diamond Armor",
    category: "body",
    cl: 10,
    weight: 14,
    physDef: 15,
    magDef: 0,
    evasion: -2,
    initiativeMod: 0,
    movementMod: -2,
    price: 9800,
    restriction: "W",
    note: ""
  },

  // ===== Shield (盾/방패) =====
  {
    id: "sh_buckler",
    name: "バックラー",
    nameKo: "버클러",
    nameEn: "Buckler",
    category: "shield",
    cl: 1,
    weight: 1,
    physDef: 2,
    magDef: 0,
    evasion: 1,
    initiativeMod: 0,
    movementMod: -1,
    price: 150,
    restriction: "W,T",
    note: ""
  },
  {
    id: "sh_kite_shield",
    name: "カイトシールド",
    nameKo: "카이트실드",
    nameEn: "Kite Shield",
    category: "shield",
    cl: 2,
    weight: 2,
    physDef: 4,
    magDef: 0,
    evasion: 0,
    initiativeMod: -1,
    movementMod: 0,
    price: 150,
    restriction: "W,A",
    note: ""
  },
  {
    id: "sh_tower_shield",
    name: "タワーシールド",
    nameKo: "타워실드",
    nameEn: "Tower Shield",
    category: "shield",
    cl: 3,
    weight: 5,
    physDef: 6,
    magDef: 0,
    evasion: -1,
    initiativeMod: -2,
    movementMod: 0,
    price: 500,
    restriction: "W",
    note: ""
  },
  {
    id: "sh_hard_shield",
    name: "ハードシールド",
    nameKo: "하드실드",
    nameEn: "Hard Shield",
    category: "shield",
    cl: 5,
    weight: 3,
    physDef: 8,
    magDef: 0,
    evasion: 0,
    initiativeMod: -1,
    movementMod: 0,
    price: 1000,
    restriction: "W",
    note: ""
  },
  {
    id: "sh_crystal_shield",
    name: "クリスタルシールド",
    nameKo: "크리스탈실드",
    nameEn: "Crystal Shield",
    category: "shield",
    cl: 9,
    weight: 3,
    physDef: 10,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 4300,
    restriction: "W,A",
    note: ""
  },

  // ===== Auxiliary (補助/보조) =====
  {
    id: "a_cloak",
    name: "マント",
    nameKo: "망토",
    nameEn: "Cloak",
    category: "auxiliary",
    cl: 1,
    weight: 1,
    physDef: 1,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 100,
    restriction: "",
    note: ""
  },
  {
    id: "a_gauntlet",
    name: "ガントレット",
    nameKo: "건틀릿",
    nameEn: "Gauntlet",
    category: "auxiliary",
    cl: 2,
    weight: 2,
    physDef: 3,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: -1,
    price: 300,
    restriction: "W,T",
    note: ""
  },
  {
    id: "a_greaves",
    name: "グリーブ",
    nameKo: "그리브",
    nameEn: "Greaves",
    category: "auxiliary",
    cl: 2,
    weight: 2,
    physDef: 2,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 0,
    price: 200,
    restriction: "W",
    note: ""
  },
  {
    id: "a_quick_band",
    name: "クイックバンド",
    nameKo: "퀵밴드",
    nameEn: "Quick Band",
    category: "auxiliary",
    cl: 4,
    weight: 2,
    physDef: 0,
    magDef: 0,
    evasion: 0,
    initiativeMod: 2,
    movementMod: 1,
    price: 1200,
    restriction: "W,A,T",
    note: ""
  },
  {
    id: "a_wing_boots",
    name: "ウイングブーツ",
    nameKo: "윙부츠",
    nameEn: "Wing Boots",
    category: "auxiliary",
    cl: 9,
    weight: 4,
    physDef: 4,
    magDef: 0,
    evasion: 0,
    initiativeMod: 0,
    movementMod: 1,
    price: 5100,
    restriction: "W,A,T",
    note: ""
  }
];

const accessories = [
  {
    id: "acc_instrument",
    name: "楽器",
    nameKo: "악기",
    nameEn: "Instrument",
    cl: 1,
    weight: 1,
    price: 50,
    effect: "Main skill cost -1 (min 1)",
    effectKo: "메인 스킬 코스트 -1 (최소 1)",
    restriction: "bard",
    note: ""
  },
  {
    id: "acc_thiefs_tool",
    name: "シーブスツール",
    nameKo: "시브스툴",
    nameEn: "Thief's Tool",
    cl: 1,
    weight: 1,
    price: 50,
    effect: "Trap disarm +1",
    effectKo: "트랩 해제 +1",
    restriction: "thief",
    note: ""
  },
  {
    id: "acc_holy_symbol",
    name: "聖印",
    nameKo: "성인",
    nameEn: "Holy Symbol",
    cl: 1,
    weight: 1,
    price: 150,
    effect: "Heal +1D",
    effectKo: "힐 +1D",
    restriction: "acolyte",
    note: ""
  },
  {
    id: "acc_grimoire",
    name: "グリモア",
    nameKo: "그리모어",
    nameEn: "Grimoire",
    cl: 1,
    weight: 1,
    price: 200,
    effect: "Magic damage +1",
    effectKo: "마법 데미지 +1",
    restriction: "mage",
    note: ""
  },
  {
    id: "acc_talisman",
    name: "タリスマン",
    nameKo: "탤리즈먼",
    nameEn: "Talisman",
    cl: 3,
    weight: 1,
    price: 5000,
    effect: "Magic check +1, magic damage +1",
    effectKo: "마법 판정 +1, 마법 데미지 +1",
    restriction: "",
    note: ""
  },
  {
    id: "acc_secret_manual",
    name: "秘伝書",
    nameKo: "비전서",
    nameEn: "Secret Manual",
    cl: 4,
    weight: 1,
    price: 1500,
    effect: "Unarmed damage +2",
    effectKo: "격투 데미지 +2",
    restriction: "monk",
    note: ""
  },
  {
    id: "acc_black_belt",
    name: "黒帯",
    nameKo: "검은띠",
    nameEn: "Black Belt",
    cl: 10,
    weight: 1,
    price: 15000,
    effect: "Unarmed damage +7",
    effectKo: "격투 데미지 +7",
    restriction: "monk",
    note: ""
  }
];

const items = [
  // ===== Potions (포션) =====
  {
    id: "item_hp_potion",
    name: "HPポーション",
    nameKo: "HP 포션",
    nameEn: "HP Potion",
    category: "potion",
    cl: 1,
    weight: 1,
    price: 30,
    effect: "Recover HP 2D",
    effectKo: "HP 2D 회복",
    note: ""
  },
  {
    id: "item_mp_potion",
    name: "MPポーション",
    nameKo: "MP 포션",
    nameEn: "MP Potion",
    category: "potion",
    cl: 1,
    weight: 1,
    price: 50,
    effect: "Recover MP 2D",
    effectKo: "MP 2D 회복",
    note: ""
  },
  {
    id: "item_high_hp_potion",
    name: "ハイHPポーション",
    nameKo: "하이 HP 포션",
    nameEn: "High HP Potion",
    category: "potion",
    cl: 1,
    weight: 1,
    price: 200,
    effect: "Recover HP 4D",
    effectKo: "HP 4D 회복",
    note: ""
  },
  {
    id: "item_high_mp_potion",
    name: "ハイMPポーション",
    nameKo: "하이 MP 포션",
    nameEn: "High MP Potion",
    category: "potion",
    cl: 1,
    weight: 1,
    price: 300,
    effect: "Recover MP 4D",
    effectKo: "MP 4D 회복",
    note: ""
  },
  {
    id: "item_ex_hp_potion",
    name: "EXHPポーション",
    nameKo: "EX HP 포션",
    nameEn: "EX HP Potion",
    category: "potion",
    cl: 2,
    weight: 1,
    price: 2000,
    effect: "Recover HP 6D",
    effectKo: "HP 6D 회복",
    note: ""
  },
  {
    id: "item_ex_mp_potion",
    name: "EXMPポーション",
    nameKo: "EX MP 포션",
    nameEn: "EX MP Potion",
    category: "potion",
    cl: 2,
    weight: 1,
    price: 3000,
    effect: "Recover MP 6D",
    effectKo: "MP 6D 회복",
    note: ""
  },
  {
    id: "item_holy_water",
    name: "聖水",
    nameKo: "성수",
    nameEn: "Holy Water",
    category: "potion",
    cl: 1,
    weight: 3,
    price: 500,
    effect: "Light attribute damage",
    effectKo: "빛 속성 데미지",
    note: ""
  },
  {
    id: "item_fire_wine",
    name: "火酒",
    nameKo: "화주",
    nameEn: "Fire Wine",
    category: "potion",
    cl: 1,
    weight: 2,
    price: 300,
    effect: "Weapon damage +2",
    effectKo: "무기 데미지 +2",
    note: ""
  },
  {
    id: "item_courage_pill",
    name: "強心丹",
    nameKo: "강심단",
    nameEn: "Courage Pill",
    category: "potion",
    cl: 1,
    weight: 3,
    price: 300,
    effect: "Spirit check +1D",
    effectKo: "정신 판정 +1D",
    note: ""
  },

  // ===== Food (음식) =====
  {
    id: "item_meat",
    name: "肉",
    nameKo: "고기",
    nameEn: "Meat",
    category: "food",
    cl: 1,
    weight: 1,
    price: 20,
    effect: "Recover HP 1D",
    effectKo: "HP 1D 회복",
    note: ""
  },
  {
    id: "item_vegetable",
    name: "野菜",
    nameKo: "채소",
    nameEn: "Vegetable",
    category: "food",
    cl: 1,
    weight: 1,
    price: 20,
    effect: "Recover MP 3",
    effectKo: "MP 3 회복",
    note: ""
  },
  {
    id: "item_fruit",
    name: "果物",
    nameKo: "과일",
    nameEn: "Fruit",
    category: "food",
    cl: 1,
    weight: 1,
    price: 30,
    effect: "Recover MP 1D",
    effectKo: "MP 1D 회복",
    note: ""
  },

  // ===== Tools (도구) =====
  {
    id: "item_lantern",
    name: "ランタン",
    nameKo: "랜턴",
    nameEn: "Lantern",
    category: "tool",
    cl: 1,
    weight: 1,
    price: 5,
    effect: "Negate darkness",
    effectKo: "어둠 무효화",
    note: ""
  },
  {
    id: "item_rope",
    name: "ロープ",
    nameKo: "로프",
    nameEn: "Rope",
    category: "tool",
    cl: 1,
    weight: 1,
    price: 3,
    effect: "Climb/Jump +2",
    effectKo: "등반/점프 +2",
    note: ""
  },
  {
    id: "item_flint",
    name: "火打石",
    nameKo: "부싯돌",
    nameEn: "Flint",
    category: "tool",
    cl: 1,
    weight: 1,
    price: 1,
    effect: "Start fire",
    effectKo: "불 피우기",
    note: ""
  },
  {
    id: "item_belt_pouch",
    name: "ベルトポーチ",
    nameKo: "벨트파우치",
    nameEn: "Belt Pouch",
    category: "container",
    cl: 1,
    weight: 1,
    price: 15,
    effect: "Carry capacity +2",
    effectKo: "소지 용량 +2",
    note: ""
  },
  {
    id: "item_backpack",
    name: "バックパック",
    nameKo: "백팩",
    nameEn: "Backpack",
    category: "container",
    cl: 1,
    weight: 1,
    price: 30,
    effect: "Carry capacity +5",
    effectKo: "소지 용량 +5",
    note: ""
  },
  {
    id: "item_dimensional_bag",
    name: "四次元バッグ",
    nameKo: "이차원백",
    nameEn: "Dimensional Bag",
    category: "container",
    cl: 1,
    weight: 1,
    price: 2000,
    effect: "Carry capacity +10",
    effectKo: "소지 용량 +10",
    note: ""
  },
  {
    id: "item_quiver",
    name: "矢筒",
    nameKo: "화살통",
    nameEn: "Quiver",
    category: "container",
    cl: 1,
    weight: 1,
    price: 100,
    effect: "Hold 5 arrows weight 0",
    effectKo: "화살 5개 무게 0으로 보관",
    note: ""
  },
  {
    id: "item_potion_holder",
    name: "ポーションホルダー",
    nameKo: "포션홀더",
    nameEn: "Potion Holder",
    category: "container",
    cl: 1,
    weight: 1,
    price: 150,
    effect: "Hold 5 potions weight 0",
    effectKo: "포션 5개 무게 0으로 보관",
    note: ""
  },

  // ===== Arrows (화살) =====
  {
    id: "item_fine_arrow",
    name: "ファインアロー",
    nameKo: "파인애로우",
    nameEn: "Fine Arrow",
    category: "arrow",
    cl: 1,
    weight: 1,
    price: 50,
    effect: "Bow damage +2",
    effectKo: "활 데미지 +2",
    note: ""
  },
  {
    id: "item_mithril_arrow",
    name: "ミスリルアロー",
    nameKo: "미스릴화살",
    nameEn: "Mithril Arrow",
    category: "arrow",
    cl: 4,
    weight: 1,
    price: 800,
    effect: "Bow damage +7",
    effectKo: "활 데미지 +7",
    note: ""
  }
];

export const equipmentLibrary = {
  weapons,
  armor,
  accessories,
  items
};
