/**
 * Skill Library for Arianrhod 2E
 * Contains all available skills from the Arianrhod 2E Rulebook (pp.89-149)
 *
 * Skill data structure:
 * - id: Unique kebab-case identifier
 * - name: Japanese katakana/kanji name
 * - nameEn: English name
 * - skillClass: Class the skill belongs to
 * - timing: When the skill can be used (matches skillTimings keys)
 * - cost: MP cost (string, "" if none)
 * - range: Range in Japanese
 * - target: Target description in Japanese
 * - maxLevel: Maximum skill level
 * - description: Effect description in Japanese
 */

export const skillLibrary = {
  general: [
    { id: "destroy", name: "ディストロイ", nameEn: "Destroy", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "オブジェクトを破壊する時のダメージに+2Dする。ただし、破壊不可オブジェクトは壊せない。" },
    { id: "connection", name: "コネクション", nameEn: "Connection", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【感知】判定で行う情報収集判定に+1Dする。" },
    { id: "camp", name: "キャンプ", nameEn: "Camp", skillClass: "general", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "シーン終了時に使用。HP回復とMP回復をかける。【HP】と【MP】を[2D+CL]点回復する。シナリオ1回。" },
    { id: "magic-lore", name: "マジック・ロアー", nameEn: "Magic Lore", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "魔術に関する事項を知っているか確認する【知力】判定に+1Dする。" },
    { id: "disarm-trap", name: "トラップ解除", nameEn: "Disarm Trap", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "トラップ解除判定に+1Dする。" },
    { id: "mp-brew", name: "MP調製", nameEn: "MP Brew", skillClass: "general", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 2, description: "SL1なら3個のMPポーション、SL2なら5個のMPポーションか2個のハイMPポーションを取得する。" },
    { id: "light", name: "ライト", nameEn: "Light", skillClass: "general", timing: "action", cost: "6", range: "効果参照", target: "効果参照", maxLevel: 1, description: "自分のいるエリアの明るさを2または3に変更する。フリーアクションで再度変更可能。元の明るさより低くはできない。シーン終了まで持続。" },
    { id: "vitality", name: "バイタリティ", nameEn: "Vitality", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【最大HP】に+CLする。《インテンション》と同時に取得できない。" },
    { id: "hiding", name: "ハイディング", nameEn: "Hiding", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "隠密状態のキャラクターを発見する時、または隠密状態の自分を発見しようとする対象との対決の【感知】判定に+1Dする。" },
    { id: "monster-lore", name: "モンスター・ロアー", nameEn: "Monster Lore", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "エネミー識別判定に+1Dする。" },
    { id: "strong-mind", name: "ストロング・マインド", nameEn: "Strong Mind", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "スキルに対するリアクションで行う【精神】判定に+1Dする。" },
    { id: "sixth-sense", name: "シックス・センス", nameEn: "Sixth Sense", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "危険感知判定に+1Dする。" },
    { id: "myth-lore", name: "ミス・ロアー", nameEn: "Myth Lore", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "神話や伝説に関する事項を知っているか確認する【知力】判定に+1Dする。" },
    { id: "bluffing", name: "ブラッフィング", nameEn: "Bluffing", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "ハッタリや嘘で騙す等の【精神】判定に+1Dする。" },
    { id: "legacy", name: "レガシー", nameEn: "Legacy", skillClass: "general", timing: "item", cost: "", range: "自身", target: "効果参照", maxLevel: 1, description: "フリープレイに装備または携帯した武器か防具を1つ選ぶ。武器なら攻撃力+1、防具なら【物理防御力】か【魔法防御力】に+1する。" },
    { id: "evade", name: "イベイド", nameEn: "Evade", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "封鎖されたインゲイジから離脱する時の【行動値】判定に+1Dする。" },
    { id: "blood-of-darkness", name: "ブラッド・オブ・ダークネス", nameEn: "Blood of Darkness", skillClass: "general", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "HP回復をかける。フェイト使用上限以下のフェイトを消費。消費したフェイト1点ごとに【HP】を[CL×2]点回復する。シーン1回。" },
    { id: "trap-sense", name: "トラップ・センス", nameEn: "Trap Sense", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "トラップ探知、トラップ解除、危険感知判定の達成値に+1する。また、自分が作動させたトラップが要求した判定の達成値に+2する。" },
    { id: "crime", name: "クライム", nameEn: "Crime", skillClass: "general", timing: "action", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "情報収集を【幸運】判定で行う。その【幸運】判定に+1Dする。" },
    { id: "alertness", name: "警戒", nameEn: "Alertness", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "奇襲攻撃を受けた時、判定に-1Dを受けずにリアクションできる。" },
    { id: "alchemy-lore", name: "アルケミー・ロアー", nameEn: "Alchemy Lore", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "錬金術に関する事項を知っているか確認する【知力】判定に+1Dする。" },
    { id: "miracle", name: "ミラクル", nameEn: "Miracle", skillClass: "general", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "判定を行った後に使用。フェイトを1点消費。その判定の達成値に+1Dする。シナリオ1回。" },
    { id: "item-lore", name: "アイテム・ロアー", nameEn: "Item Lore", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "アイテム鑑定判定に+1Dする。" },
    { id: "animal-talk", name: "アニマル・トーク", nameEn: "Animal Talk", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "「分類：動物、魔獣」のエネミーと意思疎通ができる。" },
    { id: "athletic", name: "アスレチック", nameEn: "Athletic", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "登攀や跳躍を行う【筋力】判定に+1Dする。" },
    { id: "heavy-armor", name: "ヘビー・アーマー", nameEn: "Heavy Armor", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "装備した防具の「移動修正」が0未満なら「移動修正：±0」に変更する。" },
    { id: "intention", name: "インテンション", nameEn: "Intention", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【最大MP】に+CLする。《バイタリティ》と同時に取得できない。" },
    { id: "negotiation", name: "ネゴシエーション", nameEn: "Negotiation", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "交渉や説得等の【精神】判定に+1Dする。" },
    { id: "power-lift", name: "パワー・リフト", nameEn: "Power Lift", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "携帯品の重量制限が[【筋力基本値】×2]になる。" },
    { id: "culture", name: "カルチャー", nameEn: "Culture", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "取得時にエリンの特定地域か元いた世界を1つ選ぶ。選んだ場所の文化や慣習を知っているか確認する【知力】判定に+1Dする。" },
    { id: "quick-change", name: "クイック・チェンジ", nameEn: "Quick Change", skillClass: "general", timing: "move", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "「装備部位：右手」と「装備部位：左手」に装備したアイテムを携帯品に変更し、携帯品から別のアイテムを装備する。" },
    { id: "insight", name: "インサイト", nameEn: "Insight", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "ハッタリや嘘を見抜く【精神】判定に+1Dする。" },
    { id: "guardian", name: "ガーディアン", nameEn: "Guardian", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "誰かが封鎖されたインゲイジから離脱する時、それに対するリアクション判定に+1Dする。" },
    { id: "tracker", name: "トラッカー", nameEn: "Tracker", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "残された足跡や痕跡等を追跡する時の【感知】判定に+1Dする。" },
    { id: "hp-brew", name: "HP調製", nameEn: "HP Brew", skillClass: "general", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 2, description: "SL1なら3個のHPポーション、SL2なら5個のHPポーションか2個のハイHPポーションを取得する。" },
    { id: "faith-gran-ain", name: "フェイス：グランアイン", nameEn: "Faith: Gran-Ain", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "攻撃のダメージに+2する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "training", name: "トレーニング", nameEn: "Training", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "取得時に能力基本値を1つ選ぶ。選んだ能力基本値に+3する。選んだ能力基本値ごとに別のスキルとして扱う。" },
    { id: "first-aid", name: "ファースト・エイド", nameEn: "First Aid", skillClass: "general", timing: "action", cost: "", range: "至近", target: "単体", maxLevel: 1, description: "対象が戦闘不能の時に有効。難易度10の【器用】判定に成功すると対象の戦闘不能を回復し、【HP】を1にする。対象は行動完了になる。" },
    { id: "faith-dagdemoar", name: "フェイス：ダグデモア", nameEn: "Faith: Dagdemoar", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【行動値】に+2する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "detect-trap", name: "トラップ探知", nameEn: "Detect Trap", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "トラップ探知判定に+1Dする。また、トラップ探知に失敗してもトラップが作動しない。" },
    { id: "faith-gobanon", name: "フェイス：ゴバノン", nameEn: "Faith: Gobanon", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【物理防御力】と【魔法防御力】に+1する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "faith-danan", name: "フェイス：ダナン", nameEn: "Faith: Danan", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ軽減をかけるスキル、パワーの効果に+1する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "faith-brigantia", name: "フェイス：ブリガンティア", nameEn: "Faith: Brigantia", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "リアクションの達成値に+1する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "fishing", name: "釣り", nameEn: "Fishing", skillClass: "general", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "シーン終了時に使用。MP回復をかける。【MP】を[2D+(CL×2)]点回復する。シナリオ1回。" },
    { id: "quick-drink", name: "クイック・ドリンク", nameEn: "Quick Drink", skillClass: "general", timing: "cleanup", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "「種別：ポーション」のアイテムを1個使用する。シーン1回。" },
    { id: "faith-aema", name: "フェイス：アエマ", nameEn: "Faith: Aema", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "HP回復、MP回復をかけるスキル、アイテム、パワーの効果に+2する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "hunting", name: "狩り", nameEn: "Hunting", skillClass: "general", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "シーン終了時に使用。HP回復をかける。【HP】を[2D+(CL×2)]点回復する。シナリオ1回。" },
    { id: "history", name: "ヒストリー", nameEn: "History", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "各国家や都市の概要、歴史、人物、過去の事件に関して知っているか確認する【知力】判定に+1Dする。" },
    { id: "faith-akenrab", name: "フェイス：アケンラブ", nameEn: "Faith: Akenrab", skillClass: "general", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "全ての命中判定の達成値に+1する。ただし、他の《フェイス：～～》を取得できなくなる。" },
    { id: "ether-charge", name: "エーテル・チャージ", nameEn: "Ether Charge", skillClass: "general", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "MP回復をかける。フェイト使用上限以下のフェイトを消費。消費したフェイト1点ごとに【MP】を[CL]点回復する。シーン1回。" },
  ],

  warrior: [
    { id: "bash", name: "バッシュ", nameEn: "Bash", skillClass: "warrior", timing: "action", cost: "4", range: "武器", target: "単体", maxLevel: 5, description: "対象に武器攻撃を行う。その攻撃のダメージに+[(SL)D]する。" },
    { id: "protect", name: "プロテクト", nameEn: "Protect", skillClass: "warrior", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "【物理防御力】に+[SL×3]する。この効果はシーン終了まで持続する。" },
    { id: "recover", name: "リカバー", nameEn: "Recover", skillClass: "warrior", timing: "cleanup", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "バッドステータスを1つ回復する。" },
    { id: "charge", name: "チャージ", nameEn: "Charge", skillClass: "warrior", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加をかける。武器攻撃のダメージに+[SL×3]する。ただし、リアクション判定に-1Dする。マイナーアクションで解除を宣言するか、シーン終了まで持続。" },
    { id: "power-strike", name: "パワー・ストライク", nameEn: "Power Strike", skillClass: "warrior", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加をかける。白兵攻撃のダメージに+【筋力】する。この効果はメインプロセス終了まで持続。" },
    { id: "sweep", name: "スウィープ", nameEn: "Sweep", skillClass: "warrior", timing: "action", cost: "3", range: "至近", target: "範囲", maxLevel: 3, description: "1つのインゲイジ内の対象([SL×2]体)に白兵攻撃を行う。両手使用が必要。" },
    { id: "sonic-blast", name: "ソニック・ブラスト", nameEn: "Sonic Blast", skillClass: "warrior", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃と同時に使用。その攻撃を「対象：単体※」に変更し、ダメージに+[CL×10]する。ウォリアー専用、シナリオ1回。" },
    { id: "slash", name: "スラッシュ", nameEn: "Slash", skillClass: "warrior", timing: "damage", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "武器攻撃のダメージロール直前に使用。ダメージ増加をかける。その攻撃のダメージに+[(SL×2)D]する。シーン1回。" },
    { id: "shield-attack", name: "シールド・アタック", nameEn: "Shield Attack", skillClass: "warrior", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "武器を使用した命中判定の達成値に+SL、白兵攻撃のダメージに+[SL×2]する。盾装備が必要。" },
    { id: "parrying", name: "パリング", nameEn: "Parrying", skillClass: "warrior", timing: "afterDamage", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ軽減をかける。物理ダメージを受けたダメージロール直後に使用。その物理ダメージに-[SL×3]する。" },
    { id: "arms-mastery", name: "アームズ・マスタリー", nameEn: "Arms Mastery", skillClass: "warrior", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "取得時に「長剣、両手剣、槍、斧」から1つ選ぶ。選んだ武器を使用した命中判定に+1Dする。選んだ武器ごとに別スキルとして扱うが、複数の《アームズ・マスタリー》を同時に適用できない。" },
    { id: "fortress", name: "フォートレス", nameEn: "Fortress", skillClass: "warrior", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "【物理防御力】に+[SL×2]、【魔法防御力】に+SLする。" },
    { id: "weapon-mastery", name: "ウェポン・マスタリー", nameEn: "Weapon Mastery", skillClass: "warrior", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "武器を使用した命中判定の達成値に+[SL+1]する。" },
    { id: "quick-strike", name: "クイック・ストライク", nameEn: "Quick Strike", skillClass: "warrior", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "白兵攻撃の命中判定に+1Dする。この効果はメインプロセス終了まで持続。" },
    { id: "covering", name: "カバーリング", nameEn: "Covering", skillClass: "warrior", timing: "damage", cost: "2", range: "至近", target: "単体", maxLevel: 1, description: "対象をカバーする。行動完了時でもカバー可能で、未行動時にカバーしても行動完了にならない。防御中1回。" },
    { id: "cross-cover", name: "クロス・カバー", nameEn: "Cross Cover", skillClass: "warrior", timing: "other", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "《カバーリング》と同時に使用。《カバーリング》を「射程：至近」から「射程：20m」に変更する。ただし、移動はしない。シーンSL回。" },
    { id: "defender", name: "ディフェンダー", nameEn: "Defender", skillClass: "warrior", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "回避判定に+1Dする。ただし、メジャーアクションで行う判定に-1Dする。マイナーアクションで解除を宣言するか、シーン終了まで持続。" },
    { id: "quick-defender", name: "クイック・ディフェンダー", nameEn: "Quick Defender", skillClass: "warrior", timing: "free", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "《ディフェンダー》を同時に使用する。この効果で《ディフェンダー》をフリーアクションで使用できる。" },
    { id: "strike-force", name: "ストライク・フォース", nameEn: "Strike Force", skillClass: "warrior", timing: "setup", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加をかける。白兵攻撃のダメージに+[SL×2]する。この効果はシーン終了まで持続。" },
    { id: "incitate", name: "インシテイト", nameEn: "Incitate", skillClass: "warrior", timing: "setup", cost: "4", range: "10m", target: "単体", maxLevel: 3, description: "対象の【精神】と対決する。この対決判定の達成値に+[SL×2]する。勝利すると対象に【激怒】をかける。" },
  ],

  acolyte: [
    { id: "protection", name: "プロテクション", nameEn: "Protection", skillClass: "acolyte", timing: "afterDamage", cost: "3", range: "20m", target: "単体", maxLevel: 5, description: "対象にダメージ軽減をかける。対象がダメージを受けたダメージロール直後に使用。そのダメージに-[(SL)D]する。防御中1回。" },
    { id: "faith-might", name: "フェイス・マイト", nameEn: "Faith Might", skillClass: "acolyte", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "武器を使用した命中判定の達成値に+[SL+1]する。打撃武器使用が必要。" },
    { id: "resurrection", name: "リザレクション", nameEn: "Resurrection", skillClass: "acolyte", timing: "action", cost: "10", range: "20m", target: "単体", maxLevel: 1, description: "対象が戦闘不能の時に有効。対象の戦闘不能を回復し、【HP】を[2D]点にする。対象は行動完了になる。" },
    { id: "blessing", name: "ブレッシング", nameEn: "Blessing", skillClass: "acolyte", timing: "action", cost: "6", range: "至近", target: "単体", maxLevel: 1, description: "対象の判定に+1Dする。この効果はラウンド終了まで持続。" },
    { id: "cure", name: "キュアー", nameEn: "Cure", skillClass: "acolyte", timing: "action", cost: "5", range: "20m", target: "単体", maxLevel: 1, description: "対象にかかっているバッドステータスを全て回復する。" },
    { id: "turn-undead", name: "ターン・アンデッド", nameEn: "Turn Undead", skillClass: "acolyte", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（貫通ダメージ）。対象が「分類：アンデッド、人造生物、機械」で、1点でもHPダメージを与えたら【ノックバック(2)】をかける。" },
    { id: "sacred-magic", name: "セイクリッド・マジック", nameEn: "Sacred Magic", skillClass: "acolyte", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "貫通ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "abolition", name: "アボリション", nameEn: "Abolition", skillClass: "acolyte", timing: "afterDamage", cost: "", range: "20m", target: "単体", maxLevel: 1, description: "対象がダメージを受けたダメージロール直後に使用。そのダメージを0に変更する。アコライト専用、シナリオ1回。" },
    { id: "quick-heal", name: "クイック・ヒール", nameEn: "Quick Heal", skillClass: "acolyte", timing: "initiative", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "《ヒール》を同時に使用する。この効果で《ヒール》をイニシアティブプロセスで使用できる。シーン1回。" },
    { id: "arms-mastery-strike", name: "アームズ・マスタリー：打撃", nameEn: "Arms Mastery: Strike", skillClass: "acolyte", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器を使用した命中判定に+1Dする。打撃武器使用が必要。複数の《アームズ・マスタリー》を同時に適用できない。" },
    { id: "holy-light", name: "ホーリー・ライト", nameEn: "Holy Light", skillClass: "acolyte", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（貫通ダメージ）。対象が「分類：妖魔、魔獣、魔族」で、1点でもHPダメージを与えたら【威圧】をかける。" },
    { id: "aid", name: "エイド", nameEn: "Aid", skillClass: "acolyte", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象の回避判定に+1Dする。この効果はシーン終了まで持続。" },
    { id: "holy-smash", name: "ホーリー・スマッシュ", nameEn: "Holy Smash", skillClass: "acolyte", timing: "action", cost: "3", range: "武器", target: "単体", maxLevel: 5, description: "対象に武器攻撃を行う。その攻撃のダメージに+[(SL)D]する。打撃武器使用が必要。" },
    { id: "sacred-weapon", name: "セイクリッド・ウェポン", nameEn: "Sacred Weapon", skillClass: "acolyte", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 5, description: "対象にダメージ増加をかける。対象が行う武器攻撃のダメージに+[SL×3]する。この効果はシーン終了まで持続。" },
    { id: "sacred-shield", name: "セイクリッド・シールド", nameEn: "Sacred Shield", skillClass: "acolyte", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 5, description: "使用時に【物理防御力】と【魔法防御力】のどちらかを選ぶ。対象の選んだ防御力に+[SL×2]する。この効果はシーン終了まで持続。" },
    { id: "heal", name: "ヒール", nameEn: "Heal", skillClass: "acolyte", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 1, description: "対象にHP回復をかける。対象の【HP】を[3D+CL×3]点回復する。" },
    { id: "haste", name: "ヘイスト", nameEn: "Haste", skillClass: "acolyte", timing: "setup", cost: "3", range: "20m", target: "単体", maxLevel: 5, description: "対象に行動値増加をかける。対象の【行動値】に+[(SL)D]する。この効果はラウンド終了まで持続。" },
    { id: "enchant-magic", name: "インチャント・マジック", nameEn: "Enchant Magic", skillClass: "acolyte", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 5, description: "対象にダメージ増加をかける。対象が行う魔法攻撃のダメージに+[SL×3]する。この効果はシーン終了まで持続。" },
    { id: "smashing-blow", name: "スマッシング・ブロウ", nameEn: "Smashing Blow", skillClass: "acolyte", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加をかける。白兵攻撃のダメージに+[SL×3]する。その攻撃で対象に1点でもHPダメージを与えたら【ノックバック(2)】をかける。メインプロセス終了まで持続。打撃武器使用が必要。" },
    { id: "teleport", name: "テレポート", nameEn: "Teleport", skillClass: "acolyte", timing: "action", cost: "10", range: "至近", target: "範囲（選択）", maxLevel: 5, description: "自分と対象を記憶した場所（マークポイント）へ転送する。対象は拒否可能。マークポイント上限はSL個。シーン1回。" },
  ],

  mage: [
    { id: "magicians-might", name: "マジシャンズマイト", nameEn: "Magician's Might", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "魔法攻撃のダメージに+[(SL)D]する。" },
    { id: "magic-blast", name: "マジックブラスト", nameEn: "Magic Blast", skillClass: "mage", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "「タイミング：メジャーアクション」「対象：単体」の「分類：魔術」の「対象：単体」を「対象：範囲([《マジックブラスト》のSL×2]体)」に変更する。この効果はメインプロセス終了まで持続する。" },
    { id: "magic-forge", name: "マジックフォージ", nameEn: "Magic Forge", skillClass: "mage", timing: "other", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "魔法攻撃と同時に使用する。その魔法攻撃を「対象：単体※」に変更し、ダメージに+[CL×10]する。メイジ、シナリオ1回。" },
    { id: "magic-burst", name: "マジックバースト", nameEn: "Magic Burst", skillClass: "mage", timing: "damage", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "魔法攻撃のダメージロール直前に使用する。ダメージ増加を与える。その攻撃のダメージに+[(SL×2)D]する。シーン1回。" },
    { id: "sense-magic", name: "センスマジック", nameEn: "Sense Magic", skillClass: "mage", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加を与える。魔法攻撃のダメージに+[感知]する。この効果はメインプロセス終了まで持続する。" },
    { id: "focus", name: "フォーカス", nameEn: "Focus", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "魔術判定に+1Dする。" },
    { id: "stone-bullet", name: "ストーンブリット", nameEn: "Stone Bullet", skillClass: "mage", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは[2D+5]（〈地〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[スリップ]を与える。" },
    { id: "earth-shaker", name: "アースシェイカー", nameEn: "Earth Shaker", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "〈地〉属性の魔法ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "aerial-slash", name: "エアリアルスラッシュ", nameEn: "Aerial Slash", skillClass: "mage", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。その攻撃の魔術判定に+1Dし、ダメージは[2D+5]（〈風〉属性魔法ダメージ）。" },
    { id: "aerial-saber", name: "エアリアルセイバー", nameEn: "Aerial Saber", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "〈風〉属性の魔法ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "water-lance", name: "ウォーターランス", nameEn: "Water Lance", skillClass: "mage", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは[2D+5]（〈水〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[呆然]を与える。" },
    { id: "water-master", name: "ウォーターマスター", nameEn: "Water Master", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "〈水〉属性の魔法ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "fire-bolt", name: "ファイアボルト", nameEn: "Fire Bolt", skillClass: "mage", timing: "action", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。その攻撃のダメージは[2D+10]（〈火〉属性魔法ダメージ）。" },
    { id: "fire-lord", name: "ファイアロード", nameEn: "Fire Lord", skillClass: "mage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "〈火〉属性の魔法ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "enchant-weapon", name: "インチャントウェポン", nameEn: "Enchant Weapon", skillClass: "mage", timing: "action", cost: "5", range: "20m", target: "単体", maxLevel: 1, description: "取得時に〈地〉〈水〉〈火〉〈風〉から属性を一つ選択する。《インチャントウェポン：地》のように表記し、対象が行う武器攻撃のダメージを選択した属性の魔法ダメージに変更する。この効果はシーン終了まで持続する。選択した属性ごとに別のスキルとして扱う。" },
    { id: "stone-skin", name: "ストーンスキン", nameEn: "Stone Skin", skillClass: "mage", timing: "setup", cost: "5", range: "20m", target: "単体", maxLevel: 1, description: "対象の[物理防御力]に+5する。この効果はラウンド終了まで持続する。" },
    { id: "water-veil", name: "ウォーターベール", nameEn: "Water Veil", skillClass: "mage", timing: "afterDamage", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "ダメージ軽減を与える。対象が特殊攻撃でダメージを受けたダメージロール直後に使用する。そのダメージに-10する。ラウンド1回。" },
    { id: "aerial-guard", name: "エアリアルガード", nameEn: "Aerial Guard", skillClass: "mage", timing: "judge", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "対象が射撃攻撃、「分類：魔術」に対する回避判定を行う直前に使用する。その回避判定の達成値に+5する。ラウンド1回。" },
    { id: "fly", name: "フライ", nameEn: "Fly", skillClass: "mage", timing: "action", cost: "4", range: "至近", target: "単体", maxLevel: 3, description: "対象を飛行状態にし、[移動力]に+[SL×5]mする。この効果は対象がマイナーアクションで解除を宣言するかシーン終了まで持続する。" },
    { id: "enchant-body", name: "インチャントボディ", nameEn: "Enchant Body", skillClass: "mage", timing: "action", cost: "5", range: "20m", target: "単体", maxLevel: 3, description: "使用時に[筋力][器用][敏捷]から一つ選択する。対象が選択した能力値を使用して判定する時、達成値に+[SL×2]する。この効果はシーン終了まで持続する。" },
  ],

  thief: [
    { id: "wide-attack", name: "ワイドアタック", nameEn: "Wide Attack", skillClass: "thief", timing: "action", cost: "4", range: "武器", target: "範囲（選択）", maxLevel: 5, description: "対象に武器攻撃を行う。この攻撃の対象が2体以上の時はダメージに+[SL×2]する。" },
    { id: "dodge", name: "ダッジ", nameEn: "Dodge", skillClass: "thief", timing: "other", cost: "2", range: "自身", target: "自身", maxLevel: 5, description: "回避判定と同時に使用する。その回避判定の達成値に+[SL+2]する。盾装備不可。" },
    { id: "quick-move", name: "クイックムーブ", nameEn: "Quick Move", skillClass: "thief", timing: "setup", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "戦闘移動、または離脱を行う。ただし、あなたのいるエンゲージが敵キャラクターに封鎖されていた場合、離脱はできない。" },
    { id: "dancing-hero", name: "ダンシングヒーロー", nameEn: "Dancing Hero", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "回避判定に+1Dする。" },
    { id: "assassinate", name: "アサシネイト", nameEn: "Assassinate", skillClass: "thief", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。白兵攻撃のダメージに+[SL×10]する。この効果はメインプロセス終了まで持続する。短剣使用、隠密状態。" },
    { id: "throwing", name: "スローイング", nameEn: "Throwing", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "投げによる射撃攻撃のダメージに+[SL×4]し、射程に+10mする。" },
    { id: "rapid-strike", name: "ラピッドストライク", nameEn: "Rapid Strike", skillClass: "thief", timing: "action", cost: "4", range: "武器", target: "単体", maxLevel: 3, description: "対象に武器攻撃を行う。この攻撃の命中判定に+[(SL+1)D]する。" },
    { id: "stealth-move", name: "ステルスムーブ", nameEn: "Stealth Move", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "移動しても隠密状態が解除されず、隠密状態のままエンゲージすることもできる。この効果はスキル、パワー、アイテム、ギルドサポートの効果で移動する時も有効。" },
    { id: "treasure-hunt", name: "トレジャーハント", nameEn: "Treasure Hunt", skillClass: "thief", timing: "afterDamage", cost: "3", range: "自身", target: "自身", maxLevel: 4, description: "エネミーを対象とする白兵攻撃のダメージロール直後に使用する。その攻撃の対象に設定されたドロップアイテムを一つ得る。ルール通りドロップアイテム決定ロールを行う。ドロップアイテムが設定されていないエネミーに使用すると[エネミーレベル×10]Gを得る。シナリオSL回。" },
    { id: "whip-mastery", name: "ウィップマスタリー", nameEn: "Whip Mastery", skillClass: "thief", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加を与える。武器攻撃のダメージに+【器用】する。この効果はメインプロセス終了まで持続する。鞭使用。" },
    { id: "backstab", name: "バックスタブ", nameEn: "Backstab", skillClass: "thief", timing: "action", cost: "4", range: "武器", target: "単体", maxLevel: 5, description: "対象に武器攻撃を行う。この攻撃の命中判定に+1Dし、ダメージに+[(SL)D]する。隠密状態。" },
    { id: "specialize", name: "スペシャライズ", nameEn: "Specialize", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "取得時に武器の「種別」を一つ選択する。《スペシャライズ：長剣》のように表記し、選択した武器を使用した命中判定の達成値に+SL、ダメージに+SLする。ただし、他の《スペシャライズ》は取得できなくなる。" },
    { id: "arms-mastery-thief", name: "アームズマスタリー", nameEn: "Arms Mastery", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "取得時に「短剣、鞭」から一つ選択する。《アームズマスタリー：短剣》のように表記し、選択した武器を使用した命中判定に+1Dする。選択した武器ごとに別のスキルとして扱うが、複数の《アームズマスタリー》を同時に適用することはできない。" },
    { id: "catch-rope", name: "キャッチロープ", nameEn: "Catch Rope", skillClass: "thief", timing: "action", cost: "5", range: "武器", target: "単体", maxLevel: 5, description: "対象に白兵攻撃を行う。この攻撃のダメージに+[SL×2]する。また、この攻撃で対象に1点でもHPダメージを与えたなら、あなたと対象は移動ができなくなる。この効果はあなたか対象がマイナーアクションで解除を宣言するか、シーン終了まで持続する。鞭使用。" },
    { id: "feint", name: "フェイント", nameEn: "Feint", skillClass: "thief", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "あなたの武器攻撃に対して対象が行うリアクション判定に-1Dする。この効果はメインプロセス終了まで持続する。" },
    { id: "twin-weapon", name: "ツインウェポン", nameEn: "Twin Weapon", skillClass: "thief", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "「右手」と「左手」にそれぞれ使用条件で指定した武器を装備した時に有効。装備した2つの武器の「命中修正」「攻撃力」「行動修正」を合計し、「種別」を両方持つ「装備部位：両手」の武器1つとして扱う。短剣・鞭使用。" },
    { id: "interrupt", name: "インタラプト", nameEn: "Interrupt", skillClass: "thief", timing: "other", cost: "", range: "視界", target: "単体", maxLevel: 1, description: "対象が「タイミング：パッシブ、アイテム」以外のスキルを使用すると宣言した時に使用する。そのスキルは効果を発揮せず、即座に終了する。効果を発揮しなくてもスキルは使用したものとして扱い、対象はコスト等を正常に消費する。シーフ、シナリオ1回。" },
    { id: "weak-point", name: "ウィークポイント", nameEn: "Weak Point", skillClass: "thief", timing: "damage", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "武器攻撃のダメージロール直前に使用する。ダメージ増加を与える。その攻撃のダメージに+[(SL)D]する。" },
    { id: "poison-weapon", name: "ポイズンウェポン", nameEn: "Poison Weapon", skillClass: "thief", timing: "other", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "武器攻撃と同時に使用する。その攻撃で対象に1点でもHPダメージを与えたなら[毒(SL)]を与える。この効果はメインプロセス終了まで持続する。" },
    { id: "provoke", name: "プロボーク", nameEn: "Provoke", skillClass: "thief", timing: "setup", cost: "4", range: "10m", target: "単体", maxLevel: 3, description: "対象の[精神]と対決する。この対決の判定達成値に+[SL×2]する。この対決に勝利すると対象に[激怒]を与える。" },
  ],

  gunslinger: [
    { id: "gun-spin", name: "ガンスピン", nameEn: "Gun Spin", skillClass: "gunslinger", timing: "setup", cost: "4", range: "10m", target: "単体", maxLevel: 3, description: "対象の[精神]と対決する。この対決の判定達成値に+[SL×2]する。この対決に勝利すると対象に[激怒]を与える。魔道銃装備。" },
    { id: "rapid-fire", name: "ラピッドファイア", nameEn: "Rapid Fire", skillClass: "gunslinger", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加を与える。武器攻撃のダメージに+[敏捷]する。この効果はメインプロセス終了まで持続する。魔道銃使用。" },
    { id: "revenger", name: "リベンジャー", nameEn: "Revenger", skillClass: "gunslinger", timing: "other", cost: "10", range: "自身", target: "自身", maxLevel: 1, description: "未行動・行動完了に関係なくメインプロセスを1回行う。ただし、このスキルで発生したメインプロセスではあなたのHPや戦闘不能を回復するスキルおよびアイテム等は使用できない。シナリオ1回。" },
    { id: "long-barrel", name: "ロングバレル", nameEn: "Long Barrel", skillClass: "gunslinger", timing: "item", cost: "", range: "自身", target: "効果参照", maxLevel: 1, description: "《キャリバー》で取得した「種別：魔道銃」の武器の「命中修正」に+1、「攻撃力」に+2、「行動修正」に-2する。" },
    { id: "magic-bullet", name: "マジックバレット", nameEn: "Magic Bullet", skillClass: "gunslinger", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。射撃攻撃のダメージに+[SL×2]し、ダメージを〈無〉属性魔法ダメージに変更する。この効果はメインプロセス終了まで持続する。魔道銃使用。" },
    { id: "gun-fight", name: "ガンファイト", nameEn: "Gun Fight", skillClass: "gunslinger", timing: "other", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃と同時に使用する。その攻撃の対象とエンゲージしているなら、その対象が行うリアクション判定に-1Dする。魔道銃使用。" },
    { id: "short-barrel", name: "ショートバレル", nameEn: "Short Barrel", skillClass: "gunslinger", timing: "item", cost: "", range: "自身", target: "効果参照", maxLevel: 1, description: "《キャリバー》で取得した「種別：魔道銃」の武器の「命中修正」に+2、「行動修正」に-1する。" },
    { id: "aiming", name: "エイミング", nameEn: "Aiming", skillClass: "gunslinger", timing: "setup", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "射撃攻撃の命中判定達成値に+[SL+2]する。この効果はラウンド終了まで持続する。魔道銃使用。" },
    { id: "arms-mastery-caliber", name: "アームズマスタリー：マドウジュウ", nameEn: "Arms Mastery: Caliber", skillClass: "gunslinger", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器を使用した命中判定に+1Dする。ただし、複数の《アームズマスタリー》を同時に適用することはできない。魔道銃使用。" },
    { id: "armor-piercing", name: "アーマーピアシング", nameEn: "Armor Piercing", skillClass: "gunslinger", timing: "damage", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "射撃攻撃のダメージロール直前に使用する。その攻撃を受ける対象の[物理防御力][魔法防御力]に-[SL×3]（最低0）する。魔道銃使用。" },
    { id: "over-charge", name: "オーバーチャージ", nameEn: "Over Charge", skillClass: "gunslinger", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SL×10]する。この効果はメインプロセス終了まで持続する。攻撃に使用した武器はその直後に使用不可になる。魔道銃使用。" },
    { id: "shoot-down", name: "シュートダウン", nameEn: "Shoot Down", skillClass: "gunslinger", timing: "reaction", cost: "3", range: "視界", target: "単体", maxLevel: 3, description: "対象の射撃攻撃や魔法攻撃に対して「種別：魔道銃」の武器を使用した命中判定でリアクションを行う。この対決に勝利するとあなたに対する攻撃は失敗する。魔道銃装備、シナリオSL回。" },
    { id: "knock-back", name: "ノックバック", nameEn: "Knock Back", skillClass: "gunslinger", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃で対象に1点でもHPダメージを与えたなら[ノックバック(2)]を与える。この効果はメインプロセス終了まで持続する。魔道銃使用。" },
    { id: "quick-draw", name: "クイックドロウ", nameEn: "Quick Draw", skillClass: "gunslinger", timing: "initiative", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "未行動の時に使用可能。イニシアチブプロセスにメインプロセスを行う（メインプロセス終了後に行動完了になる）。シーン1回。" },
    { id: "rapid-shot", name: "ラピッドショット", nameEn: "Rapid Shot", skillClass: "gunslinger", timing: "action", cost: "5", range: "武器", target: "[SL+1]体", maxLevel: 3, description: "対象に射撃攻撃を行う。魔道銃使用。" },
    { id: "caliber", name: "キャリバー", nameEn: "Caliber", skillClass: "gunslinger", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "キャリバー（P157）を1つ取得する。このアイテムはあなただけが装備して使用できる。" },
    { id: "gun-draw", name: "ガンドロウ", nameEn: "Gun Draw", skillClass: "gunslinger", timing: "minor", cost: "2", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃の命中判定に+1Dする。この効果はメインプロセス終了まで持続する。また、あなたは他の武器や盾を装備した状態でも即座にその武器や盾を携帯品に変更し、携帯品欄にある「種別：魔道銃」の武器を装備できる。魔道銃使用。" },
    { id: "fall-down", name: "フォールダウン", nameEn: "Fall Down", skillClass: "gunslinger", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。射撃攻撃のダメージに+[SL×2]する。また、その攻撃で対象に1点でもHPダメージを与えた場合、対象が飛行状態、騎乗状態、同乗状態ならその状態を解除する。この効果はメインプロセス終了まで持続する。" },
    { id: "twin-caliber", name: "ツインキャリバー", nameEn: "Twin Caliber", skillClass: "gunslinger", timing: "item", cost: "", range: "自身", target: "効果参照", maxLevel: 5, description: "《キャリバー》で取得した「種別：魔道銃」の武器の「攻撃力」に+[SL×3]し、[重量：6][装備部位：両手]に変更する。" },
    { id: "quick-repair", name: "クイックリペア", nameEn: "Quick Repair", skillClass: "gunslinger", timing: "free", cost: "15", range: "自身", target: "効果参照", maxLevel: 1, description: "あなたが装備または携帯した「種別：魔道銃」の武器の破壊状態または使用不可状態を回復させ、再び使用可能にする。シーン1回。" },
  ],

  ninja: [
    { id: "concentration", name: "コンセントレーション", nameEn: "Concentration", skillClass: "ninja", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "HP回復を与える。【HP】を[CL×10]点回復し、バッドステータスを全て回復する。シナリオ1回。" },
    { id: "ninpou-earthquake", name: "ニンポウ・ジシン", nameEn: "Ninpou: Earthquake", skillClass: "ninja", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。〈地〉属性魔法ダメージを与える攻撃のダメージに+[SL×2]する。その攻撃の対象に1点でもHPダメージを与えたなら[スタン]を与える。この効果はメインプロセス終了まで持続する。" },
    { id: "critical-hit", name: "クリティカルヒット", nameEn: "Critical Hit", skillClass: "ninja", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "攻撃の命中判定がクリティカルならば、クリティカルによるダメージロールのダイス追加に加えて、さらにダメージに+[(SL+1)D]する。" },
    { id: "ninpou-gale", name: "ニンポウ・シップウ", nameEn: "Ninpou: Gale", skillClass: "ninja", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。〈風〉属性の魔法ダメージを与える攻撃のダメージに+[SL×2]する。その攻撃の対象に1点でもHPダメージを与えたなら[ノックバック(1)]を与える。この効果はメインプロセス終了まで持続する。" },
    { id: "self-destruction", name: "ジバク", nameEn: "Self-Destruction", skillClass: "ninja", timing: "action", cost: "", range: "至近", target: "範囲（選択）", maxLevel: 3, description: "取得時に属性の中から一つを選択する。対象に魔法攻撃を行う。その攻撃のダメージは[2D+あなたの現在の【HP】]であり、選択した属性の魔法ダメージとなる。【HP】はダメージ段階時点の数値を使用する。また、あなたはメインプロセス終了後に【HP】が0になり、戦闘不能になる。シナリオSL回。" },
    { id: "shadow-run", name: "カゲバシリ", nameEn: "Shadow Run", skillClass: "ninja", timing: "other", cost: "6", range: "自身", target: "自身", maxLevel: 1, description: "移動直前に使用する。この移動を行う時、あなたは封鎖を受けない。また、敵キャラクターとエンゲージしてもその場所で移動を終了しなくてもよい。" },
    { id: "explosion", name: "ダイバクハツ", nameEn: "Explosion", skillClass: "ninja", timing: "action", cost: "", range: "20m", target: "範囲（選択）", maxLevel: 3, description: "対象に特殊攻撃を行う。その攻撃の命中判定は【精神】判定であり、ダメージは[2D+SL×10]（貫通ダメージ）。また、その攻撃に対するリアクション判定は必ず失敗し、「タイミング：リアクション」のスキルやアイテムも使用できない。シナリオ1回。" },
    { id: "shadow-bind", name: "カゲシバリ", nameEn: "Shadow Bind", skillClass: "ninja", timing: "setup", cost: "5", range: "20m", target: "単体", maxLevel: 3, description: "対象の[移動力]に-[SL×3]（最低0）する。この効果は対象がマイナーアクションで解除を宣言するかシーン終了まで持続する。" },
    { id: "lightfoot", name: "ケイコウジュツ", nameEn: "Lightfoot", skillClass: "ninja", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "飛行状態になる。また、飛行状態の間[移動力]に+[SL×5]mする。この効果はマイナーアクションで解除を宣言するかシーン終了まで持続する。" },
    { id: "secret-art", name: "ヒデン", nameEn: "Secret Art", skillClass: "ninja", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "攻撃の命中判定に+1Dする。この効果はメインプロセス終了まで持続する。" },
    { id: "reroll", name: "リロール", nameEn: "Reroll", skillClass: "ninja", timing: "afterDamage", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "あなたの攻撃で発生したダメージロール直後に使用する。そのダメージロールで振ったダイスの中から任意で選んだ[SL×2]個以下のダイスを振り直す。ラウンド1回。" },
    { id: "secret-technique", name: "オウギ", nameEn: "Secret Technique", skillClass: "ninja", timing: "other", cost: "5", range: "自身", target: "自身", maxLevel: 5, description: "攻撃の命中判定直後に使用する。その命中判定で振ったダイスの中から任意で選んだ3個以下のダイスを振り直す。その結果6が出たダイスが2個以上ならクリティカルになる。シナリオSL回。" },
    { id: "clone", name: "ブンシン", nameEn: "Clone", skillClass: "ninja", timing: "setup", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "回避判定の達成値に+[SL×2]する。この効果はラウンド終了まで持続する。" },
    { id: "assassin", name: "アサシン", nameEn: "Assassin", skillClass: "ninja", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "攻撃の命中判定に+1D、ダメージに+[(SL)D]する。隠密状態。" },
    { id: "ninpou-spread", name: "ニンポウ・カクサン", nameEn: "Ninpou: Spread", skillClass: "ninja", timing: "move", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "魔法攻撃の「対象：単体」を「対象：範囲（選択）」に変更する。この効果はメインプロセス終了まで持続する。シーンSL回。" },
    { id: "ninpou-power", name: "ニンポウ・イリョク", nameEn: "Ninpou: Power", skillClass: "ninja", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。魔法攻撃のダメージに+[SL×4]する。この効果はメインプロセス終了まで持続する。" },
    { id: "ninpou-fire", name: "ニンポウ・カエン", nameEn: "Ninpou: Fire", skillClass: "ninja", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。〈火〉属性の魔法ダメージを与える攻撃のダメージに+[SL×2]する。その攻撃の対象に1点でもHPダメージを与えたなら[威圧]を与える。この効果はメインプロセス終了まで持続する。" },
    { id: "insight-ninja", name: "カンパ", nameEn: "Insight", skillClass: "ninja", timing: "judge", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "攻撃の命中判定直前に使用する。その攻撃に対するリアクション判定は必ず失敗し、「タイミング：リアクション」のスキルやアイテムも使用できない。シナリオ1回。" },
    { id: "pressure-point", name: "テンケツ", nameEn: "Pressure Point", skillClass: "ninja", timing: "other", cost: "8", range: "自身", target: "自身", maxLevel: 1, description: "魔法攻撃の命中判定がクリティカルの時に使用する。その攻撃を受けた対象の[魔法防御力]を0として扱いHPダメージを算出する。" },
    { id: "ninpou-poison-fog", name: "ニンポウ・ドクム", nameEn: "Ninpou: Poison Fog", skillClass: "ninja", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。〈水〉属性魔法ダメージを与える攻撃のダメージに+[SL×2]する。その攻撃の対象に1点でもHPダメージを与えたなら[毒(1)]を与える。この効果はメインプロセス終了まで持続する。" },
  ],

  dancer: [
    { id: "scenic-star", name: "シニックスター", nameEn: "Scenic Star", skillClass: "dancer", timing: "judge", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "判定直前に使用する。その判定に+1Dする。" },
    { id: "dancing", name: "ダンシング", nameEn: "Dancing", skillClass: "dancer", timing: "judge", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "回避判定直前に使用する。その回避判定の達成値に+[SL+1]する。" },
    { id: "bizarre-dance", name: "ビザンダンス", nameEn: "Bizarre Dance", skillClass: "dancer", timing: "setup", cost: "4", range: "10m", target: "単体", maxLevel: 3, description: "対象の【精神】と対決する。この対決の判定達成値に+[SLx2]する。勝利すると対象に[激怒]を与える。" },
    { id: "step-mastery", name: "ステップマスタリー", nameEn: "Step Mastery", skillClass: "dancer", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "《ステップ:～》の効果が持続中に有効。攻撃の命中判定に+SL、回避判定に+SL、攻撃のダメージに+SLする。" },
    { id: "step-darkness", name: "ステップ：ダークネス", nameEn: "Step: Darkness", skillClass: "dancer", timing: "setup", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "回避判定の達成値に+[SLx2]する。この効果はシーン終了まで持続する。" },
    { id: "step-wind", name: "ステップ：ウィンド", nameEn: "Step: Wind", skillClass: "dancer", timing: "setup", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "【移動力】に+[SLx5]する。この効果はシーン終了まで持続する。" },
    { id: "jump", name: "ジャンプ", nameEn: "Jump", skillClass: "dancer", timing: "other", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "《フェザータップ》と同時に使用する。《フェザータップ》で移動する際の【移動力】に+10mする。" },
    { id: "step-light", name: "ステップ：ライト", nameEn: "Step: Light", skillClass: "dancer", timing: "setup", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "行動値増加を与える。【行動値】に+[SLx3]する。この効果はシーン終了まで持続する。" },
    { id: "step-water", name: "ステップ：ウォーター", nameEn: "Step: Water", skillClass: "dancer", timing: "setup", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "攻撃の命中判定達成値に+[SLx2]する。この効果はシーン終了まで持続する。" },
    { id: "sword-dance", name: "ソードダンス", nameEn: "Sword Dance", skillClass: "dancer", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加を与える。白兵攻撃のダメージに+[敏捷]する。この効果はメインプロセス終了まで持続する。" },
    { id: "step-earth", name: "ステップ：アース", nameEn: "Step: Earth", skillClass: "dancer", timing: "setup", cost: "5", range: "自身", target: "自身", maxLevel: 3, description: "【物理防御力】と【魔法防御力】に+[SLx3]する。この効果はシーン終了まで持続する。" },
    { id: "step-fire", name: "ステップ：ファイア", nameEn: "Step: Fire", skillClass: "dancer", timing: "setup", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。攻撃のダメージに+[SLx3]する。この効果はシーン終了まで持続する。" },
    { id: "quick-change-dancer", name: "クイックチェンジ", nameEn: "Quick Change", skillClass: "dancer", timing: "move", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "「装備部位:頭」と「装備部位:胴」の装備品を携帯品に変更し、携帯品の別のアイテムを「装備部位:頭」と「装備部位:胴」に装備する。片方だけでもよい。" },
    { id: "aerial-rave", name: "エアリアルレイヴ", nameEn: "Aerial Rave", skillClass: "dancer", timing: "action", cost: "7", range: "至近", target: "単体", maxLevel: 5, description: "対象に白兵攻撃を行う。この攻撃の命中判定に+1D、ダメージに+[SLx3]する。使用条件:飛行状態。" },
    { id: "street-performance-dancer", name: "ストリートパフォーマンス", nameEn: "Street Performance", skillClass: "dancer", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "フリープレイ時、所持金が[【敏捷】x100]G増える。" },
    { id: "back-step", name: "バックステップ", nameEn: "Back Step", skillClass: "dancer", timing: "other", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "回避判定と同時に使用する。回避判定の達成値に+SLする。回避成功時、5m以内に移動またはエンゲージから離脱できる。ただし封鎖されている場合は離脱不可。" },
    { id: "invite-step", name: "インバイトステップ", nameEn: "Invite Step", skillClass: "dancer", timing: "judge", cost: "10", range: "自身", target: "自身", maxLevel: 1, description: "判定直前に使用する。その判定で振るダイスの数がスキル等の効果で減少していても、その効果を受けずに判定できる。" },
    { id: "feather-tap", name: "フェザータップ", nameEn: "Feather Tap", skillClass: "dancer", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "飛行状態になり戦闘移動を行う。飛行状態になるだけで移動しなくてもよい。飛行状態はメインプロセス終了まで持続する。" },
    { id: "trance", name: "トランス", nameEn: "Trance", skillClass: "dancer", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "MP回復を与える。【MP】を[CLx5]点回復する。使用条件:シナリオ1回。" },
    { id: "encore-dancer", name: "アンコール", nameEn: "Encore", skillClass: "dancer", timing: "initiative", cost: "6", range: "20m", target: "単体", maxLevel: 1, description: "未行動のキャラクターに使用可能。対象はイニシアチブプロセスにメインプロセスを行う（終了後に行動完了）。対象はこの効果を拒否できる。使用条件:シーン1回。" },
  ],

  ranger: [
    { id: "twin-shot", name: "ツインショット", nameEn: "Twin Shot", skillClass: "ranger", timing: "other", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "射撃攻撃のダメージロール直前に使用する。「種別:矢弾」アイテムを2個消費し、そのアイテムの効果（命中やダメージ修正等）が2倍になる。" },
    { id: "hidden", name: "ヒドゥン", nameEn: "Hidden", skillClass: "ranger", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "隠密状態になる。ただし敵キャラクターとエンゲージしている場合は使用不可。" },
    { id: "long-range", name: "ロングレンジ", nameEn: "Long Range", skillClass: "ranger", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "射撃攻撃に使用した武器の「射程」に+[SLx10]mする。この効果はメインプロセスまで持続する。" },
    { id: "recycle", name: "リサイクル", nameEn: "Recycle", skillClass: "ranger", timing: "other", cost: "8", range: "自身", target: "自身", maxLevel: 1, description: "シーン終了時に使用する。そのシーンで使用した「種別:矢弾」は携帯品に、投げで使用した武器は装備品または携帯品に戻り再使用可能になる。" },
    { id: "suppression", name: "サプレション", nameEn: "Suppression", skillClass: "ranger", timing: "action", cost: "3", range: "武器", target: "単体", maxLevel: 1, description: "対象に射撃攻撃を行う。1点でもHPダメージを与えた場合、対象の回避判定に-1Dする。この効果はラウンド終了まで持続する。" },
    { id: "snipe", name: "スナイプ", nameEn: "Snipe", skillClass: "ranger", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ増加を与える。射撃攻撃のダメージに+【感知】する。この効果はメインプロセス終了まで持続する。" },
    { id: "dead-shot", name: "デッドショット", nameEn: "Dead Shot", skillClass: "ranger", timing: "other", cost: "5", range: "自身", target: "自身", maxLevel: 5, description: "射撃攻撃と同時に使用する。1点でもHPダメージを与えた場合、[SLx3]点のHPロスを与える。使用条件:隠密状態。" },
    { id: "aiming-ranger", name: "エイミング", nameEn: "Aiming", skillClass: "ranger", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。射撃攻撃の命中判定に+1D、ダメージに+SLする。この効果はメインプロセス終了まで持続する。" },
    { id: "shoot-down-ranger", name: "シュートダウン", nameEn: "Shoot Down", skillClass: "ranger", timing: "reaction", cost: "5", range: "視界", target: "単体", maxLevel: 3, description: "対象の射撃攻撃や魔法攻撃に対し、装備した武器で命中判定によるリアクションを行う。勝利すると攻撃は失敗する。使用条件:弓・錬金銃・魔導銃装備、シナリオSL回。" },
    { id: "quick-draw-ranger", name: "クイックドロウ", nameEn: "Quick Draw", skillClass: "ranger", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "装備した武器の「行動修正」が0未満なら「行動修正:±0」に変更する。使用条件:弓・錬金銃・魔導銃装備。" },
    { id: "slayer", name: "スレイヤー", nameEn: "Slayer", skillClass: "ranger", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "取得時にエネミーの「分類」を一つ選択する。選択した「分類」のキャラクターに対する武器攻撃のダメージに+[SLx4]する。選択した「分類」ごとに別スキルとして扱う。" },
    { id: "arms-mastery-bow", name: "アームズマスタリー：弓", nameEn: "Arms Mastery: Bow", skillClass: "ranger", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器を使用した命中判定に+1Dする。ただし複数の《アームズマスタリー》を同時に適用することはできない。使用条件:弓使用。" },
    { id: "rapid-fire-ranger", name: "ラピッドファイア", nameEn: "Rapid Fire", skillClass: "ranger", timing: "action", cost: "4", range: "武器", target: "範囲（選択）", maxLevel: 3, description: "一つのエンゲージ内の対象（[SLx2]体）に射撃攻撃を行う。" },
    { id: "quick-action", name: "クイックアクション", nameEn: "Quick Action", skillClass: "ranger", timing: "move", cost: "8", range: "自身", target: "自身", maxLevel: 5, description: "「タイミング:マイナーアクション」のレンジャースキルと同時に使用し、ムーブアクションとして使用できる。ただしそのメインプロセスのマイナーアクションでは該当スキルを使用不可。使用条件:シーンSL回。" },
    { id: "hit-and-away", name: "ヒットアンドアウェイ", nameEn: "Hit and Away", skillClass: "ranger", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "離脱を行う。また離脱してもマイナーアクションを行うことができる。" },
    { id: "slayer-adapt", name: "スレイヤーアダプト", nameEn: "Slayer Adapt", skillClass: "ranger", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "エネミーの「分類」を一つ選択し、取得した《スレイヤー》の一つをその「分類」に変更する。同じ「分類」の《スレイヤー》は累積しない。シーン終了まで持続。使用条件:シナリオSL回。" },
    { id: "first-aid-ranger", name: "ファストエイド", nameEn: "First Aid", skillClass: "ranger", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "HP回復を与える。【HP】を[CLx1]点回復し、バッドステータスを全て回復する。使用条件:シナリオ1回。" },
    { id: "steady", name: "ステディ", nameEn: "Steady", skillClass: "ranger", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。射撃攻撃のダメージに+[SLx3]する。この効果は移動するか、シーン終了まで持続する。" },
    { id: "hawk-eye", name: "ホークアイ", nameEn: "Hawk Eye", skillClass: "ranger", timing: "move", cost: "2", range: "自身", target: "自身", maxLevel: 5, description: "「種別:弓、錬金銃、魔導銃」を使用した命中判定の達成値および投げによる射撃攻撃の命中判定達成値に+[SL+1]する。この効果は移動するかシーン終了まで持続する。" },
    { id: "point-blank", name: "ポイントブランク", nameEn: "Point Blank", skillClass: "ranger", timing: "move", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "エンゲージしたキャラクターを対象に射撃攻撃ができる。この効果はメインプロセス終了まで持続する。" },
  ],

  monk: [
    { id: "magic-guard", name: "マジックガード", nameEn: "Magic Guard", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "【魔法防御力】に+[SLx3]する。" },
    { id: "emotional-control", name: "エモーショナルコントロール", nameEn: "Emotional Control", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【精神】に+2する。" },
    { id: "ki-strike", name: "気功撃", nameEn: "Ki Strike", skillClass: "monk", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SLx3]する。1点でもHPダメージを与えた場合[ノックバック(1)]を与える。メインプロセス終了まで持続。" },
    { id: "vital-force", name: "バイタルフォース", nameEn: "Vital Force", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "【最大HP】に+[SLx5]する。" },
    { id: "power-strike-monk", name: "強打", nameEn: "Power Strike", skillClass: "monk", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。武器攻撃のダメージに+[(SL)D]する。メインプロセス終了まで持続。使用条件:格闘使用。" },
    { id: "light-step", name: "軽功", nameEn: "Light Step", skillClass: "monk", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "HP回復を与える。【HP】を[CLx1]点回復する。使用条件:シナリオ1回。" },
    { id: "counter", name: "カウンター", nameEn: "Counter", skillClass: "monk", timing: "other", cost: "", range: "効果参照", target: "単体", maxLevel: 1, description: "攻撃のダメージを受けた直後に使用する。攻撃した対象に受けたHPダメージ分のHPロスを与える（最大値はあなたの【最大HP】）。使用条件:シナリオ1回。" },
    { id: "ki-blast", name: "気弾", nameEn: "Ki Blast", skillClass: "monk", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 5, description: "対象に白兵攻撃を行う。〈無〉属性魔法ダメージとなり、ダメージに+[SLx2]する。射程内の対象にエンゲージせず白兵攻撃可能。使用条件:格闘使用。" },
    { id: "nerve-strike", name: "精神打", nameEn: "Nerve Strike", skillClass: "monk", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SLx3]する。1点でもHPダメージを与えた場合[スタン]を与える。メインプロセス終了まで持続。" },
    { id: "deep-breath", name: "深呼吸", nameEn: "Deep Breath", skillClass: "monk", timing: "setup", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。白兵攻撃のダメージに+[(SL)D]する。ラウンド終了まで持続。使用条件:格闘使用。" },
    { id: "ki-reinforcement", name: "気功強化", nameEn: "Ki Reinforcement", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃のダメージに+【精神】する。使用条件:格闘使用。" },
    { id: "arms-mastery-brawl", name: "アームズマスタリー：格闘", nameEn: "Arms Mastery: Brawl", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器を使用した命中判定に+1Dする。ただし複数の《アームズマスタリー》を同時に適用することはできない。使用条件:格闘使用。" },
    { id: "ki-amplification", name: "気功練成", nameEn: "Ki Amplification", skillClass: "monk", timing: "damage", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "武器攻撃のダメージロール直前に使用する。[SLx5]点以内の範囲で任意の【MP】を消費（最低1）。消費した【MP】1点につきダメージに+1する。メインプロセス終了まで持続。" },
    { id: "immovable-mind", name: "不動心", nameEn: "Immovable Mind", skillClass: "monk", timing: "other", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "バッドステータスを受けた直後に使用する。そのとき受けたバッドステータスを全て回復する。使用条件:戦闘中1回。" },
    { id: "piercing-strike", name: "貫通撃", nameEn: "Piercing Strike", skillClass: "monk", timing: "action", cost: "6", range: "武器", target: "単体", maxLevel: 1, description: "対象に白兵攻撃を行う。ダメージロール時、対象の【物理防御力】と【魔法防御力】を0として扱いHPダメージを算出する。使用条件:格闘使用。" },
    { id: "pursuit", name: "追撃", nameEn: "Pursuit", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "白兵攻撃の対象にバッドステータスが付与されている場合、その攻撃のダメージに+[(SLx2)D]する。使用条件:格闘使用。" },
    { id: "throw-down", name: "背負い投げ", nameEn: "Throw Down", skillClass: "monk", timing: "action", cost: "4", range: "至近", target: "単体", maxLevel: 5, description: "対象に白兵攻撃を行う。ダメージに+[SLx2]する。命中した場合、HPダメージの有無に関わらず[スリップ]を与える。使用条件:格闘使用。" },
    { id: "iron-body", name: "金剛身", nameEn: "Iron Body", skillClass: "monk", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "【物理防御力】に+[SLx3]する。" },
    { id: "feint-strike", name: "牽制", nameEn: "Feint Strike", skillClass: "monk", timing: "judge", cost: "3", range: "自身", target: "自身", maxLevel: 5, description: "白兵攻撃の命中判定直前に使用する。その判定のダイスに+1Dする。使用条件:格闘使用、シーンSL回。" },
    { id: "provoke-monk", name: "プロボーク", nameEn: "Provoke", skillClass: "monk", timing: "setup", cost: "4", range: "10m", target: "単体", maxLevel: 3, description: "対象と【精神】対決を行う。この対決の判定達成値に+[SLx2]する。勝利すると対象に[激怒]を与える。" },
  ],

  bard: [
    { id: "select-soul", name: "セレクトソウル", nameEn: "Select Soul", skillClass: "bard", timing: "other", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "「対象:範囲」の「分類:呪歌」と同時に使用する。その呪歌の「対象:範囲」を「対象:範囲（選択）」に変更する。" },
    { id: "information", name: "インフォメーション", nameEn: "Information", skillClass: "bard", timing: "action", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "情報収集を【精神】判定で行う。その【精神】判定に+1Dする。" },
    { id: "war-cry", name: "ウォークライ", nameEn: "War Cry", skillClass: "bard", timing: "damage", cost: "4", range: "20m", target: "単体", maxLevel: 5, description: "対象の攻撃によるダメージロール直前に使用する。対象にダメージ増加を与え、その攻撃のダメージに+[(SL)D]する。増えたダイスはあなたが振る。自身は対象にできない。使用条件:ラウンド1回。" },
    { id: "lullaby", name: "ララバイ", nameEn: "Lullaby", skillClass: "bard", timing: "action", cost: "5", range: "20m", target: "範囲", maxLevel: 1, description: "対象に[スリップ]を与える。" },
    { id: "hero-song", name: "ヒーローソング", nameEn: "Hero Song", skillClass: "bard", timing: "action", cost: "6", range: "20m", target: "範囲", maxLevel: 5, description: "使用時に【物理防御力】と【魔法防御力】のどちらかを選択する。対象の選択した防御力に+[SLx2]する。シーン終了まで持続。" },
    { id: "voice-magic", name: "ボイスマジック", nameEn: "Voice Magic", skillClass: "bard", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "呪歌判定に+1Dする。" },
    { id: "siren", name: "サイレン", nameEn: "Siren", skillClass: "bard", timing: "action", cost: "5", range: "20m", target: "範囲", maxLevel: 1, description: "対象に[スタン]を与える。" },
    { id: "street-performance-bard", name: "ストリートパフォーマンス", nameEn: "Street Performance", skillClass: "bard", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "フリープレイ時、所持金が[【精神】x100]G増える。" },
    { id: "high-speed-chant", name: "ハイスピードチャント", nameEn: "High Speed Chant", skillClass: "bard", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "呪歌判定の達成値に+[SLx2]する。" },
    { id: "discord", name: "ディスコード", nameEn: "Discord", skillClass: "bard", timing: "action", cost: "5", range: "20m", target: "範囲", maxLevel: 1, description: "対象に[威圧]を与える。" },
    { id: "re-attune", name: "リアチューン", nameEn: "Re-Attune", skillClass: "bard", timing: "action", cost: "10", range: "20m", target: "範囲", maxLevel: 5, description: "使用時に属性を一つ選択する。対象の属性を選択した属性に変更する。シーン終了まで持続。使用条件:シナリオSL回。" },
    { id: "quick-change-bard", name: "クイックチェンジ", nameEn: "Quick Change", skillClass: "bard", timing: "move", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "「装備部位:補助防具」と「装備部位:装身具」の装備品を携帯品に変更し、携帯品の別のアイテムを装備する。片方だけでもよい。" },
    { id: "healing-song", name: "ヒーリングソング", nameEn: "Healing Song", skillClass: "bard", timing: "action", cost: "6", range: "20m", target: "範囲", maxLevel: 1, description: "HP回復を与える。対象の【HP】を[3D+CLx2]点回復する。" },
    { id: "lament", name: "ラメント", nameEn: "Lament", skillClass: "bard", timing: "action", cost: "8", range: "20m", target: "範囲", maxLevel: 1, description: "対象のバッドステータスを全て回復する。" },
    { id: "encore-bard", name: "アンコール", nameEn: "Encore", skillClass: "bard", timing: "setup", cost: "", range: "20m", target: "単体", maxLevel: 1, description: "対象が既に使用した、使用回数制限のあるスキル一つの使用回数を1増やす。「使用条件:シナリオ～回」のスキルのみ対象。使用条件:シナリオ1回。" },
    { id: "improvisation", name: "インプロビゼイション", nameEn: "Improvisation", skillClass: "bard", timing: "judge", cost: "7", range: "自身", target: "自身", maxLevel: 1, description: "判定直前に使用する。その判定を呪歌判定で代用判定する。使用条件:シーン1回。" },
    { id: "refresh", name: "リフレッシュ", nameEn: "Refresh", skillClass: "bard", timing: "action", cost: "7", range: "20m", target: "単体", maxLevel: 3, description: "行動完了状態のキャラクターに有効。対象を未行動状態にする。使用条件:シーンSL回。" },
    { id: "violence", name: "バイオレンス", nameEn: "Violence", skillClass: "bard", timing: "other", cost: "2", range: "自身", target: "自身", maxLevel: 5, description: "バッドステータスを与える「分類:呪歌」と同時に使用する。「対象に[SLx3]点のHPロスを与える」を追加する。" },
    { id: "ballad-of-war", name: "バラッドオブウォー", nameEn: "Ballad of War", skillClass: "bard", timing: "action", cost: "4", range: "20m", target: "範囲", maxLevel: 5, description: "ダメージ増加を与える。対象の攻撃のダメージに+[SLx2]する。シーン終了まで持続。" },
    { id: "fate-spinner", name: "フェイトスピナー", nameEn: "Fate Spinner", skillClass: "bard", timing: "other", cost: "", range: "20m", target: "単体", maxLevel: 3, description: "対象がダイスロール増加のためにフェイトを使用する直前に使用する。フェイトを1点消費。対象のダイスロールに+1Dする。自身は対象にできない。使用条件:シーンSL回。" },
  ],

  samurai: [
    { id: "magic-blade", name: "マホウケン", nameEn: "Magic Blade", skillClass: "samurai", timing: "damage", cost: "2", range: "自身", target: "自身", maxLevel: 1, description: "白兵攻撃のダメージロール直前に使用。属性を1つ選択し、その攻撃のダメージを選択した属性の魔法ダメージに変更する。刀身に魔法属性の力を込めて一撃を放つスキル。カタナ使用、シーン1回。" },
    { id: "cripple", name: "クリプル", nameEn: "Cripple", skillClass: "samurai", timing: "action", cost: "4", range: "武器", target: "単体", maxLevel: 5, description: "対象に武器攻撃を行う。この攻撃で対象に1点でもHPダメージを与えたなら、対象が行う回避判定の達成値に-[SL×2]する。この効果は対象がマイナーアクションで解除を宣言するかシーン終了まで持続。クリティカル：ダイスロール増加。" },
    { id: "deflection", name: "ハンシャ", nameEn: "Deflection", skillClass: "samurai", timing: "reaction", cost: "6", range: "視界", target: "単体", maxLevel: 3, description: "対象の射撃攻撃や魔法攻撃に対し、装備した武器を使用した命中判定でリアクションを行う。この対決に勝利すればあなたに対する攻撃は失敗する。シナリオSL回。" },
    { id: "rend", name: "レンド", nameEn: "Rend", skillClass: "samurai", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SL×10]する。この効果はメインプロセス終了まで持続し、攻撃に使用した武器はその直後破壊される。カタナ使用。" },
    { id: "sonic-boom", name: "ソニックブーム", nameEn: "Sonic Boom", skillClass: "samurai", timing: "action", cost: "4", range: "効果参照", target: "単体", maxLevel: 3, description: "対象に白兵攻撃を行う。この攻撃は「射程：[SL×10]m」であり、エンゲージしていない対象にも攻撃できる。クリティカル：ダイスロール増加。" },
    { id: "sonic-blast-samurai", name: "ソニックブラスト", nameEn: "Sonic Blast", skillClass: "samurai", timing: "other", cost: "2", range: "自身", target: "自身", maxLevel: 3, description: "《ソニックブーム》と同時に使用する。ダメージ増加を与える。該当攻撃のダメージに+[(SL)D]する。カタナ装備。" },
    { id: "counter-slash", name: "カウンタースラッシュ", nameEn: "Counter Slash", skillClass: "samurai", timing: "reaction", cost: "4", range: "武器", target: "単体", maxLevel: 3, description: "対象の白兵攻撃に対し、装備した武器を使用した命中判定でリアクションを行う。この対決に勝利すれば対象に[CL×5]のHPロスを与える。また、対象の攻撃はあなたに自動的に命中する。シーンSL回。" },
    { id: "my-katana", name: "マイカタナ", nameEn: "My Katana", skillClass: "samurai", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "「種別：カタナ」の武器をSL個取得する。このアイテムはあなただけが装備・使用できる。サムライの精神ともいえる武器カタナを所有している。" },
    { id: "quick-draw-samurai", name: "バットウ", nameEn: "Quick Draw", skillClass: "samurai", timing: "move", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "戦闘移動を行い、さらに武器を1つ装備できる。移動しながら武器を抜くスキル。" },
    { id: "armor-break", name: "アーマーブレイク", nameEn: "Armor Break", skillClass: "samurai", timing: "action", cost: "5", range: "武器", target: "単体", maxLevel: 5, description: "対象に武器攻撃を行う。この攻撃はダメージロール段階でダメージを与えず、対象の【物理防御力】に-[SL×4]（最低0）する。この効果は累積し、シーン終了まで持続。クリティカル：コスト0。" },
    { id: "arms-mastery-katana", name: "アームズマスタリー：カタナ", nameEn: "Arms Mastery: Katana", skillClass: "samurai", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "武器を使用した命中判定に+1Dする。ただし、複数の《アームズマスタリー》を同時に適用することはできない。カタナ使用。" },
    { id: "minds-eye", name: "シンガン", nameEn: "Mind's Eye", skillClass: "samurai", timing: "setup", cost: "3", range: "自身", target: "自身", maxLevel: 3, description: "リアクションの達成値に+[SL+1]する。この効果はラウンド終了まで持続。相手のあらゆる動きに対応できるようにするスキル。" },
    { id: "mushin", name: "ムシン", nameEn: "Mushin", skillClass: "samurai", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "使用時にクラスを1つ選択する。そのクラスで取得したスキルを「コスト：―」に変更する。この効果はラウンド終了まで持続。シナリオ1回。" },
    { id: "sword-guard", name: "ケンシュ", nameEn: "Sword Guard", skillClass: "samurai", timing: "afterDamage", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "ダメージ軽減を与える。あなたがダメージを受けたダメージロール直後に使用。そのダメージに-[武器の攻撃力+2]する。カタナ装備、防御中1回。" },
    { id: "initiative", name: "センセイ", nameEn: "Initiative", skillClass: "samurai", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "【行動値】に+[SL×2]する。相手より先に行動するスキル。" },
    { id: "flash-strike", name: "イッセン", nameEn: "Flash Strike", skillClass: "samurai", timing: "action", cost: "6", range: "武器", target: "範囲（選択）", maxLevel: 3, description: "対象に武器攻撃を行う。CL（またはエネミーレベル）が[CL+SL]以下のモブエネミーが対象なら、ダメージロールでダメージを与える代わりに戦闘不能または死亡させる（使用時に決定）。それ以外の対象には通常通りダメージを与える。シーン1回。クリティカル：ダイスロール増加。" },
    { id: "moonlight-slash", name: "ゲッカザン", nameEn: "Moonlight Slash", skillClass: "samurai", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SL×3]する。また、その攻撃で対象に1点でもHPダメージを与えたなら[スリップ]を与える。メインプロセス終了まで持続。" },
    { id: "intimidation", name: "イフウ", nameEn: "Intimidation", skillClass: "samurai", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SL×3]する。また、その攻撃で対象に1点でもHPダメージを与えたなら[威圧]を与える。メインプロセス終了まで持続。" },
    { id: "two-handed", name: "リョウシュ", nameEn: "Two-Handed", skillClass: "samurai", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "「装備部位：片手」で「種別：カタナ」の武器を「装備部位：両手」に変更し、「攻撃力」に+[SL×2]する。カタナ装備。" },
    { id: "ki-break", name: "キサイ", nameEn: "Ki Break", skillClass: "samurai", timing: "minor", cost: "6", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。武器攻撃のダメージに+[SL×3]する。また、その攻撃で対象に1点でもHPダメージを与えたなら[呆然]を与える。メインプロセス終了まで持続。" },
  ],

  summoner: [
    { id: "familiar-guard", name: "ファミリアガード", nameEn: "Familiar Guard", skillClass: "summoner", timing: "afterDamage", cost: "", range: "20m", target: "単体", maxLevel: 1, description: "対象にダメージ軽減を与える。対象がダメージを受けたダメージロール直後に使用。そのダメージに-[CL×5]する。ただし、携帯した使い魔1体が使用不可になる。使い魔携帯、シーン1回。" },
    { id: "animal-master", name: "アニマルマスター", nameEn: "Animal Master", skillClass: "summoner", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "サモナースキルに有効。スキルで行う判定の達成値に+[SL+1]する。動物を手懐ける才能を表すスキル。" },
    { id: "summon-circle", name: "サモンサークル", nameEn: "Summon Circle", skillClass: "summoner", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "効果をダイスで決めるスキルやパワーに有効。攻撃、HP回復、MP回復、ダメージ増加、ダメージ軽減を与える「分類：魔術」のスキル・パワーとサモナースキルの効果に+[(SL)D]する。メインプロセス終了まで持続。" },
    { id: "cost-down", name: "コストダウン", nameEn: "Cost Down", skillClass: "summoner", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "サモナースキルに有効。あなたが使用するスキルのコストに-[SL]（最低1）する。" },
    { id: "summon-simurgh", name: "サモンシムルグ", nameEn: "Summon Simurgh", skillClass: "summoner", timing: "action", cost: "8", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象にHP回復を与える。対象の【HP】を[2D+CL×2]点回復する。クリティカル：ダイスロール増加。" },
    { id: "summon-catoblepas", name: "サモンカトブレパス", nameEn: "Summon Catoblepas", skillClass: "summoner", timing: "action", cost: "8", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（〈無〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[呆然]を与える。クリティカル：ダイスロール増加。" },
    { id: "summon-grand-master", name: "サモングランドマスター", nameEn: "Summon Grand Master", skillClass: "summoner", timing: "action", cost: "4", range: "20m", target: "単体", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは[2D+10]（〈無〉属性魔法ダメージ）。また、対象が「分類：動物、魔獣、霊獣」なら、対象の【魔法防御力】を0とみなしてHPダメージを算出する。クリティカル：ダイスロール増加。" },
    { id: "summon-arachne", name: "サモンアラクネ", nameEn: "Summon Arachne", skillClass: "summoner", timing: "afterDamage", cost: "9", range: "20m", target: "範囲（選択）", maxLevel: 5, description: "対象にダメージ軽減を与える。対象がダメージを受けたダメージロール直後に使用。そのダメージに-[(SL)D]する。防御中1回。" },
    { id: "summon-fafnir", name: "サモンファブニール", nameEn: "Summon Fafnir", skillClass: "summoner", timing: "action", cost: "9", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは[2D+5]（〈無〉属性魔法ダメージ）。クリティカル：ダイスロール増加。" },
    { id: "summon-leviathan", name: "サモンリヴァイアサン", nameEn: "Summon Leviathan", skillClass: "summoner", timing: "action", cost: "8", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（〈無〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[スリップ]を与える。クリティカル：ダイスロール増加。" },
    { id: "summon-jormungandr", name: "サモンヨルムンガンド", nameEn: "Summon Jormungandr", skillClass: "summoner", timing: "action", cost: "8", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（〈無〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[毒(1)]を与える。クリティカル：ダイスロール増加。" },
    { id: "summon-fenrir", name: "サモンフェンリル", nameEn: "Summon Fenrir", skillClass: "summoner", timing: "action", cost: "8", range: "20m", target: "範囲（選択）", maxLevel: 1, description: "対象に魔法攻撃を行う。この攻撃のダメージは2D（〈無〉属性魔法ダメージ）。また、この攻撃で対象に1点でもHPダメージを与えたなら[威圧]を与える。クリティカル：ダイスロール増加。" },
    { id: "full-summon", name: "フルサモン", nameEn: "Full Summon", skillClass: "summoner", timing: "minor", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "あなたが使用する「対象：自身」以外のサモナースキルを「対象：全体（選択）」「射程：視界」に変更する。メインプロセス終了まで持続。シナリオ1回。" },
    { id: "summon-oracle", name: "サモンオラクル", nameEn: "Summon Oracle", skillClass: "summoner", timing: "action", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "GMに直接疑問点を質問できる。GMはこのスキルの効果を却下してもよい。使用を認められなければ使用回数に数えない。シナリオSL回。" },
    { id: "familiar", name: "ファミリア", nameEn: "Familiar", skillClass: "summoner", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "使い魔を[SL]個取得する。このアイテムはあなただけが携帯・使用できる。同じ能力値にボーナスを受ける使い魔を複数取得できるが、そのボーナスは同時に適用できない。" },
    { id: "familiar-strike", name: "ファミリアストライク", nameEn: "Familiar Strike", skillClass: "summoner", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "《ファミリアアタック》のダメージに+[SL×3]する。使い魔携帯。" },
    { id: "familiar-focus", name: "ファミリアフォーカス", nameEn: "Familiar Focus", skillClass: "summoner", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "《ファミリアアタック》の判定に+1Dする。使い魔携帯。" },
    { id: "familiar-attack", name: "ファミリアアタック", nameEn: "Familiar Attack", skillClass: "summoner", timing: "action", cost: "5", range: "20m", target: "単体", maxLevel: 5, description: "対象に特殊攻撃を行う。この攻撃の命中判定は【感知】判定であり、ダメージは[(SL+2)D+CL]（貫通ダメージ）。使い魔携帯。クリティカル：ダイスロール増加。" },
    { id: "force-bringer", name: "フォースブリンガー", nameEn: "Force Bringer", skillClass: "summoner", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "〈無〉属性魔法ダメージを与える魔法攻撃に有効。魔法攻撃のダメージに+[SL×4]する。" },
    { id: "overwhelm", name: "アットウ", nameEn: "Overwhelm", skillClass: "summoner", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "あなたが使用するサモナースキルに対するリアクション判定に-1Dする。メインプロセス終了まで持続。" },
  ],

  sage: [
    { id: "distract", name: "ディストラクト", nameEn: "Distract", skillClass: "sage", timing: "other", cost: "10", range: "20m", target: "単体", maxLevel: 3, description: "対象が判定を行った直後に使用。その判定の達成値に-[SL×3]（最低1）する。このスキルはあなたを対象に選択できない。シーン1回。" },
    { id: "element-change", name: "エレメントチェンジ", nameEn: "Element Change", skillClass: "sage", timing: "minor", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "使用時に属性を1つ選択する。魔法攻撃の魔法ダメージ属性を選択した属性に変更する。メインプロセス終了まで持続。" },
    { id: "total-recall", name: "トータルリコール", nameEn: "Total Recall", skillClass: "sage", timing: "other", cost: "4", range: "至近", target: "単体", maxLevel: 1, description: "対象が情報収集判定を行った直後に使用。その判定を振り直す。ダイス数は変更しない。対象はこの効果を拒否できる（その場合、使用回数に数えない）。シーン1回。" },
    { id: "biology", name: "バイオロジー", nameEn: "Biology", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "取得時にエネミーの「分類」を1つ選択する。《バイオロジー：妖魔》のように表記し、選択した「分類」のキャラクターに対する魔法攻撃ダメージに+[SL×4]する。選択した「分類」ごとに別のスキルとみなす。" },
    { id: "blood-cast", name: "ブラッドキャスト", nameEn: "Blood Cast", skillClass: "sage", timing: "damage", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "魔法攻撃のダメージロール直前に使用。ダメージ増加を与える。[SL×5]点以下の範囲で任意の【HP】を消費（最低1）し、消費した【HP】1点ごとにその攻撃のダメージに+1する。メインプロセス終了まで持続。" },
    { id: "advice", name: "アドバイス", nameEn: "Advice", skillClass: "sage", timing: "judge", cost: "", range: "20m", target: "単体", maxLevel: 5, description: "対象が判定を行う直前に使用。その判定に+1Dする。このスキルはあなたを対象に選択できない。シナリオ[SL+1]回。" },
    { id: "element-weak", name: "エレメントウィーク", nameEn: "Element Weak", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "攻撃の魔法ダメージが攻撃対象の対抗属性である時に有効。該当攻撃のダメージに+[SL×4]する。" },
    { id: "wiseman", name: "ワイズマン", nameEn: "Wiseman", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "【知力】判定のダイスを増やす一般スキルに有効。該当スキルの「効果」の「判定に+1Dする」を「判定に+2Dする」に変更する。" },
    { id: "instant-aid", name: "インスタントエイド", nameEn: "Instant Aid", skillClass: "sage", timing: "setup", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "エネミー識別を行う。この効果でエネミー識別をセットアッププロセスで使用できる。" },
    { id: "weak-point-sage", name: "ウィークポイント", nameEn: "Weak Point", skillClass: "sage", timing: "setup", cost: "8", range: "20m", target: "SL体", maxLevel: 3, description: "エネミー識別に成功したエネミーに有効。対象が行うリアクションに-1Dする。ラウンド終了まで持続。クリティカル：コスト0。" },
    { id: "investigation", name: "インベスティゲイション", nameEn: "Investigation", skillClass: "sage", timing: "action", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "情報収集を【知力】判定で行う。その【知力】判定に+1Dする。" },
    { id: "magical-boost", name: "マジュツゾウキョウ", nameEn: "Magical Boost", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "効果をダイスで決めるスキル・パワーに有効。魔法攻撃、HP回復、MP回復、ダメージ増加、ダメージ軽減を与える「分類：魔術」の効果に+[SL×2]する。" },
    { id: "long-distance", name: "ロングディスタンス", nameEn: "Long Distance", skillClass: "sage", timing: "minor", cost: "2", range: "自身", target: "自身", maxLevel: 5, description: "「射程：至近」でなく「タイミング：メジャーアクション」の「分類：魔術」の「射程」に+[SL×10]mする。メインプロセス終了まで持続。" },
    { id: "drop-shot", name: "ドロップショット", nameEn: "Drop Shot", skillClass: "sage", timing: "other", cost: "", range: "視界", target: "単体", maxLevel: 1, description: "対象がドロップアイテム決定ロールをする直前に使用。対象が行うドロップアイテム決定ロールに+1Dする。シーン1回。" },
    { id: "recovery", name: "リカバリー", nameEn: "Recovery", skillClass: "sage", timing: "other", cost: "5", range: "20m", target: "単体", maxLevel: 5, description: "対象の判定でファンブルが発生した直後に使用。その判定を振り直す。ダイス数は変更しない。対象はこの効果を拒否できる（その場合、使用回数に数えない）。シーンSL回。" },
    { id: "total-identify", name: "トータルアイデンティファイ", nameEn: "Total Identify", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "「対象：全体（選択）」「射程：視界」の全対象にエネミー識別を行える。エネミー識別判定は1回のみ行い、各エネミーの「識別値」と比較して成否を決定する。" },
    { id: "defense-check", name: "ディフェンスチェック", nameEn: "Defense Check", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "エネミー識別に成功した時、そのエネミーの【物理防御力】と【魔法防御力】の数値も分かる。" },
    { id: "accumulate", name: "アキュムレイト", nameEn: "Accumulate", skillClass: "sage", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 3, description: "【知力】判定の達成値に+[SL×2]する。" },
    { id: "tactics", name: "タクティクス", nameEn: "Tactics", skillClass: "sage", timing: "setup", cost: "6", range: "20m", target: "範囲（選択）", maxLevel: 5, description: "対象に行動値増加を与える。対象の【行動値】に+[SL×2]する。ラウンド終了まで持続。このスキルはあなたを対象に選択できない。クリティカル：コスト0。" },
    { id: "versatile", name: "バンノウ", nameEn: "Versatile", skillClass: "sage", timing: "judge", cost: "6", range: "自身", target: "自身", maxLevel: 1, description: "判定直前に使用。該当判定を【知力】判定で代用判定する。シーン1回。" },
  ],

  alchemist: [
    { id: "gunsmith", name: "ガンスミス", nameEn: "Gunsmith", skillClass: "alchemist", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "マスケットを1個取得する。このアイテムはあなただけが装備・使用できる。あなたは自作の錬金銃を持っている。" },
    { id: "custom-grenade", name: "カスタムグレネード", nameEn: "Custom Grenade", skillClass: "alchemist", timing: "item", cost: "", range: "効果参照", target: "効果参照", maxLevel: 1, description: "《ハンドグレネード》で取得したハンドグレネードの「攻撃力」に+CLする。" },
    { id: "selective-blast", name: "セレクティブブラスト", nameEn: "Selective Blast", skillClass: "alchemist", timing: "minor", cost: "3", range: "自身", target: "自身", maxLevel: 1, description: "射撃攻撃を「対象：範囲」から「対象：範囲（選択）」に変更する。メインプロセス終了まで持続。ハンドグレネード使用。" },
    { id: "stun-grenade", name: "スタングレネード", nameEn: "Stun Grenade", skillClass: "alchemist", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "ダメージ増加を与える。射撃攻撃のダメージに+[SL×3]する。また、その攻撃で対象に1点でもHPダメージを与えたなら[スタン]を与える。メインプロセス終了まで持続。ハンドグレネード使用。" },
    { id: "potion-spread", name: "ポーションスプレッド", nameEn: "Potion Spread", skillClass: "alchemist", timing: "action", cost: "6", range: "至近", target: "範囲（選択）", maxLevel: 1, description: "携帯した「種別：ポーション」アイテムを対象に使用する。このスキルはあなたを対象に選択できない。効果を受けたくない対象は回避判定を行い、勝利すれば効果を受けない。クリティカル：コスト0。" },
    { id: "quick-circle", name: "クイックサークル", nameEn: "Quick Circle", skillClass: "alchemist", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "錬金術判定に+1Dする。瞬間的に錬金術の標識を描いて成功率を高めるスキル。" },
    { id: "poison-grenade", name: "ポイズングレネード", nameEn: "Poison Grenade", skillClass: "alchemist", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 3, description: "射撃攻撃の対象に1点でもHPダメージを与えたなら[毒(SL)]を与える。メインプロセス終了まで持続。ハンドグレネード使用。" },
    { id: "double-potion", name: "ダブルポーション", nameEn: "Double Potion", skillClass: "alchemist", timing: "move", cost: "5", range: "自身", target: "自身", maxLevel: 1, description: "1回のアクションで「種別：ポーション」アイテムを2個使用できる。また、「種別：ポーション」を使用するスキルでも2個のポーションを使用できる。メインプロセス終了まで持続。" },
    { id: "arms-mastery-alchemy", name: "アームズマスタリー：レンキンジュツ", nameEn: "Arms Mastery: Alchemy", skillClass: "alchemist", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "取得時に「錬金銃、錬金術」から1つ選択する。選択した武器を使用した命中判定に+1Dする。選択した武器ごとに別スキルとみなすが、複数の《アームズマスタリー》を同時に適用することはできない。" },
    { id: "philosophers-stone", name: "ケンジャノイシ", nameEn: "Philosopher's Stone", skillClass: "alchemist", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "武器攻撃のダメージに+[SL×2]する。錬金銃・錬金術使用。" },
    { id: "protect-gear", name: "プロテクトギア", nameEn: "Protect Gear", skillClass: "alchemist", timing: "action", cost: "6", range: "自身", target: "自身", maxLevel: 5, description: "使用時に【物理防御力】と【魔法防御力】のいずれかを選択する。選択した防御力に+[(SL)D]する。スキル使用時にダイスを振って増加数値を決定。シーン終了まで持続。クリティカル：ダイスロール増加。" },
    { id: "enchant-weapon-alchemist", name: "マリョクフヨ", nameEn: "Enchant Weapon", skillClass: "alchemist", timing: "minor", cost: "4", range: "自身", target: "自身", maxLevel: 1, description: "武器攻撃のダメージを〈無〉属性の魔法ダメージに変更する。メインプロセス終了まで持続。" },
    { id: "potion-master", name: "ポーションマスター", nameEn: "Potion Master", skillClass: "alchemist", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "ダイスを振って効果を決めるアイテムのみ有効。「種別：ポーション」のアイテム効果に+1Dする。" },
    { id: "conversion-rifle", name: "コンバージョン：ライフル", nameEn: "Conversion: Rifle", skillClass: "alchemist", timing: "item", cost: "", range: "効果参照", target: "効果参照", maxLevel: 5, description: "《ガンスミス》で取得した「種別：錬金銃」の武器名を「ライフル」に変更する。その武器の「攻撃力」に+[SL×2]し、「射程：50m」に変更する。ただし、他の《コンバージョン》は取得できない。" },
    { id: "potion-shot", name: "ポーションショット", nameEn: "Potion Shot", skillClass: "alchemist", timing: "action", cost: "3", range: "20m", target: "単体", maxLevel: 1, description: "携帯した「種別：ポーション」アイテムを対象に使用する。効果を受けたくない対象は回避判定を行い、勝利すれば効果を受けない。クリティカル：コスト0。" },
    { id: "craft-weapon", name: "クラフトウェポン", nameEn: "Craft Weapon", skillClass: "alchemist", timing: "minor", cost: "7", range: "自身", target: "自身", maxLevel: 5, description: "使用時に「短剣、長剣、斧、打撃、槍、鞭、カタナ」から1つ選択。武器を1個製作して装備する。このアイテムはシーン終了時に消滅する。種別：選択した種別/錬金術、レベル1、重量0、命中修正±0、攻撃力+[【器用】+SL×2]、行動修正±0、射程：至近、装備部位：片手。" },
    { id: "conversion-railgun", name: "コンバージョン：レールガン", nameEn: "Conversion: Railgun", skillClass: "alchemist", timing: "item", cost: "", range: "効果参照", target: "効果参照", maxLevel: 5, description: "《ガンスミス》で取得した「種別：錬金銃」の武器名を「レールガン」に変更する。その武器の「命中修正」に+SLし、「射程：60m」に変更する。他の《コンバージョン》は取得できない。" },
    { id: "hand-grenade", name: "ハンドグレネード", nameEn: "Hand Grenade", skillClass: "alchemist", timing: "item", cost: "", range: "自身", target: "自身", maxLevel: 5, description: "ハンドグレネードを[SL×3]個取得する。このアイテムはあなただけが装備・使用できる。" },
    { id: "power-up", name: "パワーアップ", nameEn: "Power Up", skillClass: "alchemist", timing: "action", cost: "8", range: "自身", target: "自身", maxLevel: 5, description: "ダメージ増加を与える。武器攻撃のダメージに+[(SL)D]する。スキル使用時にダイスを振って増加数値を決定。シーン終了まで持続。クリティカル：ダイスロール増加。" },
    { id: "poison-master", name: "ポイズンマスター", nameEn: "Poison Master", skillClass: "alchemist", timing: "passive", cost: "", range: "自身", target: "自身", maxLevel: 1, description: "あなたが与える[毒]の効果強度に+1する。" },
  ],

};
